import { describe, expect, it, beforeEach } from 'bun:test';
import 'fake-indexeddb/auto';
import { runOnce } from './orchestrator.ts';
import {
  _resetInsightStoreForTest,
  listUndismissed,
} from './insight-store.ts';
import { drainQueue } from './queue.ts';
import type { AmbientConfig, Analyser, Insight } from './types.ts';

const NOW = 1_700_000_000_000;

function makeConfig(over: Partial<AmbientConfig> = {}): AmbientConfig {
  return {
    enabled: true,
    intervalMs: 24 * 60 * 60 * 1000,
    collections: ['entries'],
    analysers: ['trend'],
    ...over,
  };
}

function makeRows(n: number): Record<string, unknown>[] {
  const rows: Record<string, unknown>[] = [];
  for (let i = 0; i < n; i++) {
    rows.push({ ts: NOW - i * 60_000, amount: i });
  }
  return rows;
}

function syncAnalyser(
  id: 'trend' | 'anomaly',
  insightsToReturn: Insight[],
): Analyser {
  return {
    id,
    syncable: true,
    async run() {
      return insightsToReturn;
    },
  };
}

function aiAnalyser(
  id: 'sentiment-trend' | 'topic-cluster',
  insightsToReturn: Insight[],
): Analyser {
  return {
    id,
    syncable: false,
    async run() {
      return insightsToReturn;
    },
  };
}

function makeInsight(over: Partial<Insight> = {}): Insight {
  return {
    id: `i-${Math.random().toString(36).slice(2, 10)}`,
    collection: 'entries',
    generatedAt: NOW,
    urgency: 'medium',
    title: 'Synthetic insight',
    summary: 'Generated by a stub analyser for tests.',
    ...over,
  };
}

beforeEach(async () => {
  await _resetInsightStoreForTest();
});

describe('runOnce', () => {
  it('returns zeros immediately when config.enabled is false', async () => {
    let readCalled = 0;
    const result = await runOnce({
      config: makeConfig({ enabled: false }),
      analysers: [syncAnalyser('trend', [makeInsight()])],
      readCollection: async () => {
        readCalled += 1;
        return makeRows(10);
      },
      now: NOW,
    });
    expect(result.ranAnalysers).toBe(0);
    expect(result.queuedAnalysers).toBe(0);
    expect(result.insightsAppended).toBe(0);
    expect(readCalled).toBe(0);
    const stored = await listUndismissed();
    expect(stored).toEqual([]);
  });

  it('skips a collection that returns fewer than 5 rows', async () => {
    let analyserRan = 0;
    const analyser: Analyser = {
      id: 'trend',
      syncable: true,
      async run() {
        analyserRan += 1;
        return [makeInsight()];
      },
    };
    const result = await runOnce({
      config: makeConfig(),
      analysers: [analyser],
      readCollection: async () => makeRows(4),
      now: NOW,
    });
    expect(analyserRan).toBe(0);
    expect(result.ranAnalysers).toBe(0);
    expect(result.insightsAppended).toBe(0);
    const stored = await listUndismissed();
    expect(stored).toEqual([]);
  });

  it('runs a syncable analyser and persists its insights', async () => {
    const insight = makeInsight({ id: 'trend-1', title: 'spike' });
    const analyser = syncAnalyser('trend', [insight]);
    const result = await runOnce({
      config: makeConfig(),
      analysers: [analyser],
      readCollection: async () => makeRows(10),
      now: NOW,
    });
    expect(result.ranAnalysers).toBe(1);
    expect(result.queuedAnalysers).toBe(0);
    expect(result.insightsAppended).toBe(1);
    const stored = await listUndismissed();
    expect(stored).toHaveLength(1);
    expect(stored[0]?.id).toBe('trend-1');
    expect(stored[0]?.title).toBe('spike');
  });

  it('queues a syncable=false analyser when no embed/sentiment is provided', async () => {
    const analyser = aiAnalyser('topic-cluster', [makeInsight()]);
    const result = await runOnce({
      config: makeConfig({ analysers: ['topic-cluster'] }),
      analysers: [analyser],
      readCollection: async () => makeRows(10),
      now: NOW,
    });
    expect(result.ranAnalysers).toBe(0);
    expect(result.queuedAnalysers).toBe(1);
    expect(result.insightsAppended).toBe(0);
    const queued = await drainQueue();
    expect(queued).toHaveLength(1);
    expect(queued[0]?.analyserId).toBe('topic-cluster');
    expect(queued[0]?.collection).toBe('entries');
    expect(queued[0]?.cursorTs).toBe(NOW);
    expect(queued[0]?.enqueuedAt).toBe(NOW);
  });

  it('queues sentiment-trend when sentiment is missing even if embed is present', async () => {
    const analyser = aiAnalyser('sentiment-trend', [makeInsight()]);
    const result = await runOnce({
      config: makeConfig({ analysers: ['sentiment-trend'] }),
      analysers: [analyser],
      readCollection: async () => makeRows(10),
      embed: async () => ({ embedding: [0.1] }),
      now: NOW,
    });
    expect(result.queuedAnalysers).toBe(1);
    expect(result.ranAnalysers).toBe(0);
    const queued = await drainQueue();
    expect(queued).toHaveLength(1);
    expect(queued[0]?.analyserId).toBe('sentiment-trend');
  });

  it('runs a syncable=false analyser when embed is provided', async () => {
    const insight = makeInsight({ id: 'topic-1' });
    const analyser = aiAnalyser('topic-cluster', [insight]);
    const result = await runOnce({
      config: makeConfig({ analysers: ['topic-cluster'] }),
      analysers: [analyser],
      readCollection: async () => makeRows(10),
      embed: async () => ({ embedding: [0.1, 0.2, 0.3] }),
      now: NOW,
    });
    expect(result.ranAnalysers).toBe(1);
    expect(result.queuedAnalysers).toBe(0);
    expect(result.insightsAppended).toBe(1);
    const stored = await listUndismissed();
    expect(stored).toHaveLength(1);
    expect(stored[0]?.id).toBe('topic-1');
    const queued = await drainQueue();
    expect(queued).toEqual([]);
  });

  it('runs sentiment-trend when sentiment helper is provided', async () => {
    const insight = makeInsight({ id: 'sent-1' });
    const analyser = aiAnalyser('sentiment-trend', [insight]);
    const result = await runOnce({
      config: makeConfig({ analysers: ['sentiment-trend'] }),
      analysers: [analyser],
      readCollection: async () => makeRows(10),
      sentiment: async () => ({ sentiment: 'negative', score: 0.8 }),
      now: NOW,
    });
    expect(result.ranAnalysers).toBe(1);
    expect(result.queuedAnalysers).toBe(0);
    expect(result.insightsAppended).toBe(1);
  });

  it('a failing analyser does not crash the orchestrator; other analysers still run', async () => {
    const failing: Analyser = {
      id: 'trend',
      syncable: true,
      async run() {
        throw new Error('boom');
      },
    };
    const succeeding: Analyser = {
      id: 'anomaly',
      syncable: true,
      async run() {
        return [makeInsight({ id: 'anomaly-1' })];
      },
    };
    const result = await runOnce({
      config: makeConfig({ analysers: ['trend', 'anomaly'] }),
      analysers: [failing, succeeding],
      readCollection: async () => makeRows(10),
      now: NOW,
    });
    expect(result.ranAnalysers).toBe(1);
    expect(result.insightsAppended).toBe(1);
    const stored = await listUndismissed();
    expect(stored).toHaveLength(1);
    expect(stored[0]?.id).toBe('anomaly-1');
  });

  it('ignores analysers whose id is not in config.analysers', async () => {
    const trend = syncAnalyser('trend', [makeInsight({ id: 'should-run' })]);
    const anomaly = syncAnalyser('anomaly', [
      makeInsight({ id: 'should-not-run' }),
    ]);
    const result = await runOnce({
      config: makeConfig({ analysers: ['trend'] }),
      analysers: [trend, anomaly],
      readCollection: async () => makeRows(10),
      now: NOW,
    });
    expect(result.ranAnalysers).toBe(1);
    expect(result.insightsAppended).toBe(1);
    const stored = await listUndismissed();
    expect(stored).toHaveLength(1);
    expect(stored[0]?.id).toBe('should-run');
  });

  it('iterates every configured collection', async () => {
    const seen: string[] = [];
    const analyser: Analyser = {
      id: 'trend',
      syncable: true,
      async run(ctx) {
        seen.push(ctx.collection);
        return [makeInsight({ id: `${ctx.collection}-1`, collection: ctx.collection })];
      },
    };
    const result = await runOnce({
      config: makeConfig({ collections: ['entries', 'meals'] }),
      analysers: [analyser],
      readCollection: async () => makeRows(10),
      now: NOW,
    });
    expect(result.ranAnalysers).toBe(2);
    expect(result.insightsAppended).toBe(2);
    expect(seen.sort()).toEqual(['entries', 'meals']);
  });

  it('passes the 30-day window as the sinceMs argument to readCollection', async () => {
    let received: { name: string; sinceMs: number } | null = null;
    const analyser = syncAnalyser('trend', []);
    await runOnce({
      config: makeConfig(),
      analysers: [analyser],
      readCollection: async (name, sinceMs) => {
        received = { name, sinceMs };
        return makeRows(10);
      },
      now: NOW,
    });
    expect(received).not.toBeNull();
    expect(received!.name).toBe('entries');
    expect(received!.sinceMs).toBe(NOW - 30 * 24 * 3600 * 1000);
  });
});
