-- Auto-generated by scripts/new-showcase.mjs.
-- Adds 'caffeine-log' to the marketplace as a first-party showcase.

INSERT OR IGNORE INTO apps (id, slug, name, tagline, description, type, category, theme_color, background_color, source_type, source_kind, maker_id, visibility_scope, is_archived)
SELECT lower(hex(randomblob(16))), 'caffeine-log', 'Caffeine Log', 'Caffeine Log — generated showcase. Replace this once the app does something.', 'Caffeine Log — generated showcase. Replace this once the app does something.', 'app', 'utilities', '#8B5A3C', '#FAF7EF', 'zip', 'static', users.id, 'public', 0
FROM users WHERE email = 'devanteprov@gmail.com' LIMIT 1;
--> statement-breakpoint
UPDATE apps SET latest_deploy_status = 'success' WHERE slug = 'caffeine-log';
