-- Auto-generated by scripts/new-showcase.mjs.
-- Adds 'mood-pulse' to the marketplace as a first-party showcase.

INSERT OR IGNORE INTO apps (id, slug, name, tagline, description, type, category, theme_color, background_color, source_type, source_kind, maker_id, visibility_scope, is_archived)
SELECT lower(hex(randomblob(16))), 'mood-pulse', 'Mood Pulse', 'Mood Pulse — generated showcase. Replace this once the app does something.', 'Mood Pulse — generated showcase. Replace this once the app does something.', 'app', 'utilities', '#B45CB6', '#FAF7EF', 'zip', 'static', users.id, 'public', 0
FROM users WHERE email = 'devanteprov@gmail.com' LIMIT 1;
--> statement-breakpoint
UPDATE apps SET latest_deploy_status = 'success' WHERE slug = 'mood-pulse';
