-- Auto-generated by scripts/new-showcase.mjs.
-- Adds 'restaurant-memory' to the marketplace as a first-party showcase.

INSERT OR IGNORE INTO apps (id, slug, name, tagline, description, type, category, theme_color, background_color, source_type, source_kind, maker_id, visibility_scope, is_archived)
SELECT lower(hex(randomblob(16))), 'restaurant-memory', 'Restaurant Memory', 'Restaurant Memory — generated showcase. Replace this once the app does something.', 'Restaurant Memory — generated showcase. Replace this once the app does something.', 'app', 'utilities', '#A86060', '#FAF7EF', 'zip', 'static', users.id, 'public', 0
FROM users WHERE email = 'devanteprov@gmail.com' LIMIT 1;
--> statement-breakpoint
UPDATE apps SET latest_deploy_status = 'success' WHERE slug = 'restaurant-memory';
