-- P6C — refresh marketplace metadata for the 11 P4 showcase apps.
--
-- Migrations 0012-0021 were generated by scripts/new-showcase.mjs and
-- carry placeholder taglines / descriptions ("generated showcase —
-- replace this once the app does something"). Now that each P4 app has
-- real behaviour, this migration replaces the placeholders with copy
-- that matches what the user will actually see on /apps and the
-- maker dashboard.
--
-- Idempotent: every UPDATE matches by slug and overwrites the columns
-- that should change; the seed rows themselves are unchanged.

UPDATE apps
SET tagline = 'Single tap to log a coffee or tea.',
    description = 'A one-tap caffeine logger. Provides caffeine-logged so Sleep Logger can correlate timing and Mood Pulse can score the day.',
    category = 'health-fitness'
WHERE slug = 'caffeine-log';
--> statement-breakpoint
UPDATE apps
SET tagline = 'Daily water target with cooked-meal nudges.',
    description = 'Tap to log a glass. Subscribes to cooked-meal so the daily target nudges +1 after dinner.',
    category = 'health-fitness'
WHERE slug = 'hydration';
--> statement-breakpoint
UPDATE apps
SET tagline = 'Three-second mood tap with cross-app correlation.',
    description = 'Provides mood-logged. Live correlation overlay surfaces against caffeine, workout, and sleep events.',
    category = 'health-fitness'
WHERE slug = 'mood-pulse';
--> statement-breakpoint
UPDATE apps
SET tagline = 'Aches, allergies, headaches with severity heatmap.',
    description = 'Severity heatmap over 8 weeks surfaces patterns. Provides symptom-logged for downstream analytics apps.',
    category = 'health-fitness'
WHERE slug = 'symptom-tracker';
--> statement-breakpoint
UPDATE apps
SET tagline = 'DeviceMotion step count without double-counting gym.',
    description = "Subscribes to workout-completed and excludes overlapping windows from the daily count. Provides walked.",
    category = 'health-fitness'
WHERE slug = 'steps-counter';
--> statement-breakpoint
UPDATE apps
SET tagline = '25/5 cycle, broadcasts focus-session on completion.',
    description = 'Classic Pomodoro with a long break every 4 cycles. Phase boundaries fire navigate textures so you feel the transitions.',
    category = 'productivity'
WHERE slug = 'pomodoro';
--> statement-breakpoint
UPDATE apps
SET tagline = 'Save articles via the SSRF-guarded proxy.',
    description = 'Pastes a URL, fetches via /__shippie/proxy, runs Readability extraction, stores locally. Mood-logged subscription suggests short reads.',
    category = 'productivity'
WHERE slug = 'read-later';
--> statement-breakpoint
UPDATE apps
SET tagline = 'Morning rundown: 9 intents on one screen.',
    description = 'Subscribes to nine cross-app intents and surfaces agent insights with the source-data invariant. Renders one screen at 8am.',
    category = 'productivity'
WHERE slug = 'daily-briefing';
--> statement-breakpoint
UPDATE apps
SET tagline = 'Photos + notes per restaurant, on-device only.',
    description = 'Photos and coordinates persist in IndexedDB only; dined-out broadcast carries name + rating. Tracks home-vs-out ratio against cooked-meal.',
    category = 'lifestyle'
WHERE slug = 'restaurant-memory';
--> statement-breakpoint
UPDATE apps
SET tagline = 'Mesh-only ephemeral scratchpad.',
    description = 'Anyone in a Nearby room drops content. Auto-clears 30s after the room empties. Nothing persists across sessions.',
    category = 'social'
WHERE slug = 'show-and-tell';
