-- Auto-generated by scripts/new-showcase.mjs.
-- Adds 'market-demo' as a private, direct-link first-party showcase.

INSERT OR IGNORE INTO apps (id, slug, name, tagline, description, type, category, theme_color, background_color, source_type, source_kind, maker_id, visibility_scope, surface, is_archived)
SELECT lower(hex(randomblob(16))), 'market-demo', 'Highbury Market Guide', 'Real food. Local people. Every Sunday.', 'A weekly community market guide for stalls, events, visitor info, and digital loyalty stamps.', 'app', 'food-drink', '#E8603C', '#F7F3EE', 'zip', 'static', users.id, 'private', 'archived', 0
FROM users
WHERE email = 'devante@urthly.digital' OR email = 'devanteprov@gmail.com'
ORDER BY email = 'devanteprov@gmail.com' DESC
LIMIT 1;
--> statement-breakpoint
UPDATE apps
SET
  visibility_scope = 'private',
  surface = 'archived',
  is_archived = 0,
  latest_deploy_status = 'success',
  updated_at = datetime('now')
WHERE slug = 'market-demo';
