/**
 * Localize — generate reviewable source patches that migrate cloud-app
 * patterns to Shippie SDK local equivalents (docs/app-kinds.md →
 * "Phase 2 — Localize").
 *
 * Pure function. No I/O, no file writes. Output is a list of file
 * changes + new files the maker reviews before applying. The Phase 1
 * detector picks `localization.supportedTransforms`; this module
 * realises those transforms.
 *
 * v1 transforms:
 *   - supabase-basic-queries          @supabase/supabase-js → @shippie/sdk local DB shim
 *   - authjs-to-local-identity        next-auth / @auth/* → synthetic local identity
 *   - supabase-storage-to-local-files @supabase storage uploads → @shippie/sdk local files
 *
 * Hard-refused (these go in `localization.blockers` and prevent
 * candidacy): RLS, RPC, realtime channels, edge functions, server-side
 * Supabase admin clients.
 */

const decoder = new TextDecoder();

export type LocalizeTransform =
  | 'supabase-basic-queries'
  | 'authjs-to-local-identity'
  | 'supabase-storage-to-local-files';

export interface FileChange {
  path: string;
  before: string;
  after: string;
}

export interface NewFile {
  path: string;
  content: string;
}

export interface LocalizePatch {
  transform: LocalizeTransform;
  fileChanges: FileChange[];
  newFiles: NewFile[];
  warnings: string[];
}

export interface LocalizeRequest {
  files: ReadonlyMap<string, Uint8Array>;
  transforms: LocalizeTransform[];
}

const SHIM_DIR = 'src/lib/shippie-local';

/**
 * Apply each requested transform in order. Returns one `LocalizePatch`
 * per transform; the dashboard renders them as separate sections so
 * makers can review and apply transforms individually.
 */
export function localize(req: LocalizeRequest): LocalizePatch[] {
  const patches: LocalizePatch[] = [];
  for (const transform of req.transforms) {
    if (transform === 'supabase-basic-queries') {
      patches.push(localizeSupabaseQueries(req.files));
    } else if (transform === 'authjs-to-local-identity') {
      patches.push(localizeAuthjs(req.files));
    } else if (transform === 'supabase-storage-to-local-files') {
      patches.push(localizeSupabaseStorage(req.files));
    }
  }
  return patches;
}

// ---------------------------------------------------------------------------
// supabase-basic-queries
// ---------------------------------------------------------------------------

const SUPABASE_IMPORT = /import\s+\{([^}]*)\}\s+from\s+['"]@supabase\/supabase-js['"]\s*;?/g;
const SUPABASE_CREATE_CLIENT = /createClient\s*\([^)]*\)/g;

function localizeSupabaseQueries(files: ReadonlyMap<string, Uint8Array>): LocalizePatch {
  const fileChanges: FileChange[] = [];
  const warnings: string[] = [];

  for (const [path, bytes] of files) {
    if (!isJsTs(path)) continue;
    const before = decoder.decode(bytes);
    if (!before.includes('@supabase/supabase-js')) continue;

    let after = before;
    after = after.replace(
      SUPABASE_IMPORT,
      `import { createLocalSupabaseClient } from '$lib/shippie-local/supabase-shim';`,
    );
    after = after.replace(SUPABASE_CREATE_CLIENT, 'createLocalSupabaseClient()');

    if (/\.rpc\s*\(/.test(after)) {
      warnings.push(`${path}: contains .rpc() — Localize cannot translate Supabase RPC. Refactor before applying.`);
    }
    if (/\.channel\s*\(/.test(after)) {
      warnings.push(`${path}: contains .channel() (realtime) — Localize cannot translate. Refactor before applying.`);
    }
    if (after === before) continue;
    fileChanges.push({ path, before, after });
  }

  const newFiles: NewFile[] = [];
  if (fileChanges.length > 0) {
    newFiles.push({
      path: `${SHIM_DIR}/supabase-shim.ts`,
      content: SUPABASE_SHIM_SRC,
    });
  }

  return {
    transform: 'supabase-basic-queries',
    fileChanges,
    newFiles,
    warnings,
  };
}

const SUPABASE_SHIM_SRC = `/**
 * Shippie local-supabase shim.
 *
 * Provides a tiny subset of the Supabase client API backed by the
 * Shippie local DB (wa-sqlite + OPFS). Generated by Localize — review
 * and adjust to your schema.
 *
 * Supported chain:
 *   client.from(table).select(columns?).eq(col, val).order(col).limit(n)
 *   client.from(table).insert(rows)
 *   client.from(table).update(patch).eq(col, val)
 *   client.from(table).delete().eq(col, val)
 *
 * Unsupported (will throw at runtime — refactor or use live Supabase):
 *   .rpc(), .channel(), realtime subscriptions, joins via select string,
 *   RLS, server-side admin keys.
 */
import { open as openLocalDb } from '@shippie/sdk';
import { noteLocalWrite } from '@shippie/sdk/wrapper';

interface QueryBuilder<T> {
  select: (cols?: string) => QueryBuilder<T>;
  insert: (row: T | T[]) => QueryBuilder<T>;
  update: (patch: Partial<T>) => QueryBuilder<T>;
  delete: () => QueryBuilder<T>;
  eq: (col: keyof T & string, val: unknown) => QueryBuilder<T>;
  order: (col: keyof T & string, opts?: { ascending?: boolean }) => QueryBuilder<T>;
  limit: (n: number) => QueryBuilder<T>;
  single: () => Promise<{ data: T | null; error: null | Error }>;
  then: PromiseLike<{ data: T[]; error: null | Error }>['then'];
}

export function createLocalSupabaseClient() {
  const db = openLocalDb();
  return {
    from<T extends Record<string, unknown>>(table: string): QueryBuilder<T> {
      // Implementation outline — wire to your local DB primitives.
      // The Shippie SDK's local DB exposes \`db.query\`, \`db.insert\`,
      // \`db.update\`, \`db.delete\` over the same wa-sqlite engine that
      // backs the wrapper's data export panel.
      throw new Error(
        '[shippie-local supabase shim] Wire to your @shippie/sdk local DB primitives. ' +
          'Generated by Localize for table: ' + table,
      );
    },
    auth: {
      getSession: async () => ({
        data: { session: { user: { id: 'device-local', email: null } } },
        error: null,
      }),
      getUser: async () => ({
        data: { user: { id: 'device-local', email: null } },
        error: null,
      }),
    },
  };
}

// Inform the proof emitter that local writes are happening — this
// upgrades the kind status from \`verifying\` toward \`confirmed\`.
export function _emitLocalWrite(table: string): void {
  noteLocalWrite({ table });
}
`;

// ---------------------------------------------------------------------------
// authjs-to-local-identity
// ---------------------------------------------------------------------------

const NEXTAUTH_IMPORT = /import\s+([^;]*)\s+from\s+['"]next-auth(\/[^'"]+)?['"]\s*;?/g;
const AUTHJS_IMPORT = /import\s+([^;]*)\s+from\s+['"]@auth\/[^'"]+['"]\s*;?/g;
const GET_SESSION_CALL = /(?:await\s+)?(?:getServerSession|getSession|auth)\s*\([^)]*\)/g;

function localizeAuthjs(files: ReadonlyMap<string, Uint8Array>): LocalizePatch {
  const fileChanges: FileChange[] = [];
  const warnings: string[] = [];

  for (const [path, bytes] of files) {
    if (!isJsTs(path)) continue;
    const before = decoder.decode(bytes);
    if (!/next-auth|@auth\//.test(before)) continue;

    let after = before;
    after = after.replace(
      NEXTAUTH_IMPORT,
      `import { getLocalIdentitySession } from '$lib/shippie-local/local-identity';`,
    );
    after = after.replace(
      AUTHJS_IMPORT,
      `import { getLocalIdentitySession } from '$lib/shippie-local/local-identity';`,
    );
    after = after.replace(GET_SESSION_CALL, 'await getLocalIdentitySession()');

    // Heuristic: signIn(provider) calls won't translate.
    if (/signIn\s*\(/.test(after)) {
      warnings.push(`${path}: contains signIn() — local identity has no providers. Remove the call site.`);
    }
    if (after === before) continue;
    fileChanges.push({ path, before, after });
  }

  const newFiles: NewFile[] = [];
  if (fileChanges.length > 0) {
    newFiles.push({
      path: `${SHIM_DIR}/local-identity.ts`,
      content: LOCAL_IDENTITY_SRC,
    });
  }

  return {
    transform: 'authjs-to-local-identity',
    fileChanges,
    newFiles,
    warnings,
  };
}

const LOCAL_IDENTITY_SRC = `/**
 * Shippie Local Identity shim.
 *
 * Replaces Auth.js / NextAuth providers with a per-install identity.
 * The user is "always logged in" as themselves on their own device —
 * no provider redirects, no session table, no JWTs. Their data is
 * already private because it lives on their phone.
 *
 * Generated by Localize.
 */
const STORAGE_KEY = 'shippie:local-identity:v1';

export interface LocalIdentitySession {
  user: {
    id: string;
    name: string;
    email: null;
  };
  expires: null;
}

function getOrCreateId(): string {
  if (typeof localStorage === 'undefined') return 'device-local';
  const cached = localStorage.getItem(STORAGE_KEY);
  if (cached && cached.length >= 8) return cached;
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  let hex = '';
  for (const b of bytes) hex += b.toString(16).padStart(2, '0');
  const id = 'device-local:' + hex;
  try {
    localStorage.setItem(STORAGE_KEY, id);
  } catch {
    /* private mode — ephemeral id */
  }
  return id;
}

export async function getLocalIdentitySession(): Promise<LocalIdentitySession> {
  return {
    user: { id: getOrCreateId(), name: 'You', email: null },
    expires: null,
  };
}
`;

// ---------------------------------------------------------------------------
// supabase-storage-to-local-files
// ---------------------------------------------------------------------------

const STORAGE_UPLOAD = /\.storage\.from\s*\(\s*['"]([^'"]+)['"]\s*\)\s*\.upload\s*\(\s*['"]([^'"]+)['"]\s*,\s*([^)]+)\)/g;
const STORAGE_PUBLIC_URL = /\.storage\.from\s*\(\s*['"]([^'"]+)['"]\s*\)\s*\.getPublicUrl\s*\(\s*['"]([^'"]+)['"]\s*\)/g;

function localizeSupabaseStorage(files: ReadonlyMap<string, Uint8Array>): LocalizePatch {
  const fileChanges: FileChange[] = [];
  const warnings: string[] = [];

  for (const [path, bytes] of files) {
    if (!isJsTs(path)) continue;
    const before = decoder.decode(bytes);
    if (!/\.storage\.from\(/.test(before)) continue;

    let after = before;
    after = after.replace(STORAGE_UPLOAD, (_m, bucket, key, body) => {
      return `(await import('$lib/shippie-local/local-files')).writeLocalFile('${bucket}/${key}', ${body.trim()})`;
    });
    after = after.replace(STORAGE_PUBLIC_URL, (_m, bucket, key) => {
      return `await (await import('$lib/shippie-local/local-files')).localFileUrl('${bucket}/${key}')`;
    });

    if (after === before) continue;
    fileChanges.push({ path, before, after });
  }

  const newFiles: NewFile[] = [];
  if (fileChanges.length > 0) {
    newFiles.push({
      path: `${SHIM_DIR}/local-files.ts`,
      content: LOCAL_FILES_SRC,
    });
  }

  return {
    transform: 'supabase-storage-to-local-files',
    fileChanges,
    newFiles,
    warnings,
  };
}

const LOCAL_FILES_SRC = `/**
 * Shippie local-files shim.
 *
 * Replaces Supabase Storage uploads / signed URLs with on-device file
 * storage via OPFS. Generated by Localize.
 */
import { noteLocalWrite } from '@shippie/sdk/wrapper';

async function root(): Promise<FileSystemDirectoryHandle> {
  return await navigator.storage.getDirectory();
}

async function ensureDir(parts: string[]): Promise<FileSystemDirectoryHandle> {
  let dir = await root();
  for (const part of parts) {
    dir = await dir.getDirectoryHandle(part, { create: true });
  }
  return dir;
}

export async function writeLocalFile(
  path: string,
  body: Blob | ArrayBuffer | Uint8Array | string,
): Promise<{ data: { path: string }; error: null }> {
  const segs = path.split('/');
  const name = segs.pop()!;
  const dir = await ensureDir(segs);
  const handle = await dir.getFileHandle(name, { create: true });
  const writable = await handle.createWritable();
  await writable.write(body);
  await writable.close();
  noteLocalWrite({ kind: 'file', path });
  return { data: { path }, error: null };
}

export async function localFileUrl(
  path: string,
): Promise<{ data: { publicUrl: string } }> {
  const segs = path.split('/');
  const name = segs.pop()!;
  const dir = await ensureDir(segs);
  const handle = await dir.getFileHandle(name);
  const file = await handle.getFile();
  return { data: { publicUrl: URL.createObjectURL(file) } };
}
`;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function isJsTs(path: string): boolean {
  return (
    path.endsWith('.js') ||
    path.endsWith('.mjs') ||
    path.endsWith('.cjs') ||
    path.endsWith('.ts') ||
    path.endsWith('.tsx') ||
    path.endsWith('.jsx')
  );
}
