/**
 * Per-table configuration for the Postgres → D1 mirror.
 *
 * Tables are listed in dependency order (parents before children) so
 * the mirror can run a straight INSERT loop without disabling foreign
 * keys.
 *
 * Each entry declares:
 *  - table: the SQL table name (same in Postgres and SQLite per the port)
 *  - columns: the SQLite column list, in the order the INSERT statement
 *             should use. These must exist on both sides.
 *  - jsonCols / timestampCols / boolCols / arrayCols: type hints that
 *             feed into transformRow. Keep these matched to the
 *             Postgres source schema.
 *
 * NOTE: The SQLite `apps` table includes columns that don't exist in
 * the Postgres source (e.g. `latest_deploy_status` is derived). The
 * mirror only writes the columns listed here.
 */

export interface TableSpec {
  table: string;
  columns: readonly string[];
  jsonCols: ReadonlySet<string>;
  timestampCols: ReadonlySet<string>;
  boolCols: ReadonlySet<string>;
  arrayCols: ReadonlySet<string>;
  /** Optional WHERE clause to skip soft-deleted / partition-pseudo rows. */
  whereClause?: string;
}

const set = (cols: string[]) => new Set(cols);

export const TABLE_SPECS: readonly TableSpec[] = [
  // ---- Tier 1: tables with no foreign-key dependencies ----
  {
    table: 'reserved_slugs',
    columns: ['slug', 'reason', 'created_at'],
    jsonCols: set([]),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'users',
    columns: [
      'id',
      'email',
      'email_verified',
      'github_id',
      'google_id',
      'apple_id',
      'name',
      'image',
      'username',
      'bio',
      'verified_maker',
      'verification_source',
      'first_deploy_at',
      'first_deploy_duration_ms',
      'first_deploy_app_id',
      'created_at',
      'updated_at',
    ],
    jsonCols: set([]),
    timestampCols: set([
      'email_verified',
      'first_deploy_at',
      'created_at',
      'updated_at',
    ]),
    boolCols: set(['verified_maker']),
    arrayCols: set([]),
  },
  {
    table: 'organizations',
    columns: [
      'id',
      'slug',
      'name',
      'plan',
      'billing_customer_id',
      'verified_business',
      'verified_at',
      'verified_domain',
      'support_email',
      'privacy_policy_url',
      'terms_url',
      'data_residency',
      'created_at',
      'updated_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['verified_at', 'created_at', 'updated_at']),
    boolCols: set(['verified_business']),
    arrayCols: set([]),
  },

  // ---- Tier 2: depend on users / organizations ----
  {
    table: 'organization_members',
    columns: ['org_id', 'user_id', 'role', 'invited_by', 'joined_at'],
    jsonCols: set([]),
    timestampCols: set(['joined_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'organization_invites',
    columns: [
      'id',
      'org_id',
      'email',
      'role',
      'token_hash',
      'expires_at',
      'accepted_at',
      'invited_by',
      'created_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['expires_at', 'accepted_at', 'created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'audit_log',
    columns: [
      'id',
      'organization_id',
      'actor_user_id',
      'action',
      'target_type',
      'target_id',
      'metadata',
      'ip_hash',
      'created_at',
    ],
    jsonCols: set(['metadata']),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'accounts',
    columns: [
      'user_id',
      'type',
      'provider',
      'provider_account_id',
      'refresh_token',
      'access_token',
      'expires_at',
      'token_type',
      'scope',
      'id_token',
      'session_state',
    ],
    jsonCols: set([]),
    timestampCols: set([]),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'verification_tokens',
    columns: ['identifier', 'token', 'expires'],
    jsonCols: set([]),
    timestampCols: set(['expires']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'cli_device_codes',
    columns: [
      'device_code',
      'user_code',
      'user_id',
      'client_name',
      'scopes',
      'approved_at',
      'expires_at',
      'consumed_at',
      'created_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['approved_at', 'expires_at', 'consumed_at', 'created_at']),
    boolCols: set([]),
    arrayCols: set(['scopes']),
  },
  {
    table: 'cli_tokens',
    columns: [
      'id',
      'user_id',
      'token_hash',
      'client_name',
      'scopes',
      'last_used_at',
      'revoked_at',
      'expires_at',
      'created_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['last_used_at', 'revoked_at', 'expires_at', 'created_at']),
    boolCols: set([]),
    arrayCols: set(['scopes']),
  },
  {
    table: 'github_installations',
    columns: [
      'id',
      'github_installation_id',
      'user_id',
      'organization_id',
      'account_login',
      'account_type',
      'repository_selection',
      'permissions',
      'suspended_at',
      'created_at',
      'updated_at',
    ],
    jsonCols: set(['permissions']),
    timestampCols: set(['suspended_at', 'created_at', 'updated_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'store_account_credentials',
    columns: [
      'id',
      'subject_type',
      'subject_id',
      'platform',
      'credential_type',
      'label',
      'encrypted_value',
      'metadata',
      'created_at',
      'rotated_at',
    ],
    jsonCols: set(['metadata']),
    timestampCols: set(['created_at', 'rotated_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },

  // ---- Tier 3: depend on users + organizations ----
  {
    table: 'apps',
    columns: [
      'id',
      'slug',
      'name',
      'tagline',
      'description',
      'type',
      'category',
      'icon_url',
      'theme_color',
      'background_color',
      'github_repo',
      'github_branch',
      'github_installation_id',
      'github_verified',
      'source_type',
      'source_kind',
      'upstream_url',
      'upstream_config',
      'backend_type',
      'backend_url',
      'conflict_policy',
      'maker_id',
      'organization_id',
      'visibility_scope',
      'is_archived',
      'takedown_reason',
      'latest_deploy_id',
      'latest_deploy_status',
      'active_deploy_id',
      'preview_deploy_id',
      'upvote_count',
      'comment_count',
      'install_count',
      'active_users_30d',
      'feedback_open_count',
      'ranking_score_app',
      'ranking_score_web_app',
      'ranking_score_website',
      'native_readiness_score',
      'compatibility_score',
      'native_readiness_report',
      'best_on',
      'quick_ship_slo_hit',
      'support_email',
      'privacy_policy_url',
      'terms_url',
      'data_residency',
      'screenshot_urls',
      'first_published_at',
      'last_deployed_at',
      'created_at',
      'updated_at',
      'is_trial',
      'trial_until',
      'trial_claimed_by',
      'trial_ip_hash',
    ],
    jsonCols: set(['upstream_config', 'native_readiness_report']),
    timestampCols: set([
      'first_published_at',
      'last_deployed_at',
      'created_at',
      'updated_at',
      'trial_until',
    ]),
    boolCols: set(['github_verified', 'is_archived', 'quick_ship_slo_hit', 'is_trial']),
    arrayCols: set(['screenshot_urls']),
  },

  // ---- Tier 4: depend on apps ----
  {
    table: 'app_permissions',
    columns: [
      'app_id',
      'auth',
      'storage',
      'files',
      'notifications',
      'analytics',
      'external_network',
      'allowed_connect_domains',
      'native_bridge_features',
      'updated_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['updated_at']),
    boolCols: set(['auth', 'files', 'notifications', 'analytics', 'external_network']),
    arrayCols: set(['allowed_connect_domains', 'native_bridge_features']),
  },
  {
    table: 'deploys',
    columns: [
      'id',
      'app_id',
      'version',
      'commit_sha',
      'source_type',
      'shippie_json',
      'changelog',
      'status',
      'build_log',
      'preflight_status',
      'preflight_report',
      'autopackaging_status',
      'autopackaging_report',
      'error_message',
      'duration_ms',
      'source_kind',
      'source_ref',
      'csp_header',
      'created_at',
      'completed_at',
      'created_by',
    ],
    jsonCols: set(['shippie_json', 'preflight_report', 'autopackaging_report']),
    timestampCols: set(['created_at', 'completed_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'deploy_artifacts',
    columns: [
      'id',
      'deploy_id',
      'r2_prefix',
      'file_count',
      'total_bytes',
      'manifest',
      'created_at',
    ],
    jsonCols: set(['manifest']),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'oauth_clients',
    columns: [
      'id',
      'app_id',
      'client_id',
      'client_secret_hash',
      'redirect_uris',
      'allowed_scopes',
      'created_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set(['redirect_uris', 'allowed_scopes']),
  },
  {
    table: 'oauth_consents',
    columns: [
      'id',
      'user_id',
      'app_id',
      'scope',
      'consented_at',
      'revoked_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['consented_at', 'revoked_at']),
    boolCols: set([]),
    arrayCols: set(['scope']),
  },
  {
    table: 'oauth_authorization_codes',
    columns: [
      'code',
      'client_id',
      'user_id',
      'redirect_uri',
      'code_challenge',
      'scope',
      'expires_at',
      'used',
    ],
    jsonCols: set([]),
    timestampCols: set(['expires_at']),
    boolCols: set(['used']),
    arrayCols: set(['scope']),
  },
  {
    table: 'app_sessions',
    columns: [
      'id',
      'handle_hash',
      'user_id',
      'app_id',
      'scope',
      'user_agent',
      'ip_hash',
      'device_fingerprint',
      'created_at',
      'last_seen_at',
      'expires_at',
      'revoked_at',
      'rotated_from',
    ],
    jsonCols: set([]),
    timestampCols: set([
      'created_at',
      'last_seen_at',
      'expires_at',
      'revoked_at',
    ]),
    boolCols: set([]),
    arrayCols: set(['scope']),
  },
  {
    table: 'app_data',
    columns: [
      'id',
      'app_id',
      'user_id',
      'collection',
      'key',
      'data',
      'is_public',
      'created_at',
      'updated_at',
    ],
    jsonCols: set(['data']),
    timestampCols: set(['created_at', 'updated_at']),
    boolCols: set(['is_public']),
    arrayCols: set([]),
  },
  {
    table: 'app_files',
    columns: [
      'id',
      'app_id',
      'user_id',
      'filename',
      'r2_key',
      'size_bytes',
      'mime_type',
      'created_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'app_signing_configs',
    columns: [
      'id',
      'app_id',
      'platform',
      'account_credential_id',
      'is_active',
      'version',
      'ios_bundle_id',
      'ios_team_id',
      'ios_signing_mode',
      'ios_certificate_r2_key',
      'ios_certificate_password_encrypted',
      'ios_provisioning_profile_r2_key',
      'ios_entitlements_plist_r2_key',
      'android_package',
      'android_keystore_r2_key',
      'android_keystore_password_encrypted',
      'android_key_alias',
      'android_key_password_encrypted',
      'created_at',
      'updated_at',
      'created_by',
    ],
    jsonCols: set([]),
    timestampCols: set(['created_at', 'updated_at']),
    boolCols: set(['is_active']),
    arrayCols: set([]),
  },
  {
    table: 'ios_verify_kits',
    columns: [
      'id',
      'app_id',
      'signing_config_id',
      'nonce',
      'secret',
      'kit_version',
      'issued_to',
      'issued_at',
      'expires_at',
      'consumed_at',
      'consumption_outcome',
      'rejection_reason',
    ],
    jsonCols: set([]),
    timestampCols: set(['issued_at', 'expires_at', 'consumed_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'ios_signing_verifications',
    columns: [
      'id',
      'app_id',
      'signing_config_id',
      'nonce',
      'succeeded_at',
      'failed_at',
      'failure_reason',
      'xcode_version',
      'macos_version',
      'log_r2_key',
      'verify_kit_version',
      'invalidated_at',
      'invalidated_reason',
    ],
    jsonCols: set([]),
    timestampCols: set(['succeeded_at', 'failed_at', 'invalidated_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'compliance_checks',
    columns: [
      'id',
      'app_id',
      'platform',
      'check_type',
      'status',
      'evidence',
      'checked_at',
    ],
    jsonCols: set(['evidence']),
    timestampCols: set(['checked_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'privacy_manifests',
    columns: [
      'id',
      'app_id',
      'deploy_id',
      'collected_data',
      'accessed_apis',
      'tracking_enabled',
      'tracking_domains',
      'data_safety_android',
      'generated_at',
      'source',
    ],
    jsonCols: set(['collected_data', 'accessed_apis', 'data_safety_android']),
    timestampCols: set(['generated_at']),
    boolCols: set(['tracking_enabled']),
    arrayCols: set(['tracking_domains']),
  },
  {
    table: 'account_deletion_requests',
    columns: [
      'id',
      'app_id',
      'user_id',
      'requested_at',
      'grace_period_ends_at',
      'confirmed_at',
      'executed_at',
      'cancelled_at',
    ],
    jsonCols: set([]),
    timestampCols: set([
      'requested_at',
      'grace_period_ends_at',
      'confirmed_at',
      'executed_at',
      'cancelled_at',
    ]),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'native_bundles',
    columns: [
      'id',
      'app_id',
      'platform',
      'wrapper',
      'version',
      'build_number',
      'bundle_id',
      'signed_artifact_r2_key',
      'readiness_score',
      'readiness_report',
      'native_bridge_features',
      'submission_status',
      'rejection_reason',
      'store_connect_id',
      'play_console_id',
      'testflight_group',
      'play_track',
      'submitted_at',
      'approved_at',
      'created_at',
    ],
    jsonCols: set(['readiness_report']),
    timestampCols: set(['submitted_at', 'approved_at', 'created_at']),
    boolCols: set([]),
    arrayCols: set(['native_bridge_features']),
  },
  {
    table: 'push_subscriptions',
    columns: [
      'id',
      'user_id',
      'app_id',
      'endpoint',
      'p256dh',
      'auth_key',
      'created_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'app_external_domains',
    columns: ['app_id', 'deploy_id', 'domain', 'source', 'allowed', 'first_seen_at'],
    jsonCols: set([]),
    timestampCols: set(['first_seen_at']),
    boolCols: set(['allowed']),
    arrayCols: set([]),
  },
  {
    table: 'function_deployments',
    columns: [
      'id',
      'app_id',
      'deploy_id',
      'name',
      'worker_name',
      'bundle_hash',
      'bundle_r2_key',
      'allowed_domains',
      'env_schema',
      'deployed_at',
    ],
    jsonCols: set(['env_schema']),
    timestampCols: set(['deployed_at']),
    boolCols: set([]),
    arrayCols: set(['allowed_domains']),
  },
  {
    table: 'function_secrets',
    columns: [
      'id',
      'app_id',
      'key',
      'value_encrypted',
      'created_by',
      'created_at',
      'updated_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['created_at', 'updated_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'function_logs',
    columns: [
      'id',
      'app_id',
      'function_name',
      'method',
      'status',
      'duration_ms',
      'cpu_time_ms',
      'user_id',
      'error',
      'metadata',
      'created_at',
    ],
    jsonCols: set(['metadata']),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'feedback_items',
    columns: [
      'id',
      'app_id',
      'user_id',
      'type',
      'status',
      'rating',
      'title',
      'body',
      'vote_count',
      'duplicate_of',
      'external_user_id',
      'external_user_display',
      'metadata',
      'created_at',
      'updated_at',
    ],
    jsonCols: set(['metadata']),
    timestampCols: set(['created_at', 'updated_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'feedback_votes',
    columns: [
      'id',
      'feedback_id',
      'user_id',
      'external_user_id',
      'value',
      'created_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'analytics_events',
    columns: [
      'id',
      'app_id',
      'user_id',
      'session_id',
      'event_name',
      'properties',
      'url',
      'referrer',
      'created_at',
    ],
    jsonCols: set(['properties']),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'custom_domains',
    columns: [
      'id',
      'app_id',
      'domain',
      'is_canonical',
      'verification_token',
      'verified_at',
      'ssl_provisioned',
      'created_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['verified_at', 'created_at']),
    boolCols: set(['is_canonical', 'ssl_provisioned']),
    arrayCols: set([]),
  },
  {
    table: 'app_events',
    columns: [
      'id',
      'app_id',
      'session_id',
      'user_id',
      'event_type',
      'metadata',
      'ts',
    ],
    jsonCols: set(['metadata']),
    timestampCols: set(['ts']),
    boolCols: set([]),
    arrayCols: set([]),
    // Cap retention window — anything older than 60d gets dropped by the
    // SQLite retention cron anyway, so don't pay to mirror it.
    whereClause: "ts > now() - interval '60 days'",
  },
  {
    table: 'usage_daily',
    columns: ['app_id', 'day', 'event_type', 'count'],
    jsonCols: set([]),
    timestampCols: set(['day']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'wrapper_push_subscriptions',
    columns: ['endpoint', 'app_id', 'user_id', 'keys', 'created_at'],
    jsonCols: set(['keys']),
    timestampCols: set(['created_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'app_ratings',
    columns: ['app_id', 'user_id', 'rating', 'review', 'created_at', 'updated_at'],
    jsonCols: set([]),
    timestampCols: set(['created_at', 'updated_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'user_touch_graph',
    columns: ['app_a', 'app_b', 'users', 'updated_at'],
    jsonCols: set([]),
    timestampCols: set(['updated_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'app_access',
    columns: [
      'id',
      'app_id',
      'user_id',
      'email',
      'invited_by',
      'granted_at',
      'revoked_at',
      'source',
    ],
    jsonCols: set([]),
    timestampCols: set(['granted_at', 'revoked_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
  {
    table: 'app_invites',
    columns: [
      'id',
      'app_id',
      'token',
      'kind',
      'email',
      'created_by',
      'created_at',
      'expires_at',
      'max_uses',
      'used_count',
      'revoked_at',
    ],
    jsonCols: set([]),
    timestampCols: set(['created_at', 'expires_at', 'revoked_at']),
    boolCols: set([]),
    arrayCols: set([]),
  },
];
