/**
 * First-party showcase slugs. Generated by `scripts/prepare-showcases.mjs`
 * so hooks, marketplace URLs, and offline precache share one source of
 * truth.
 *
 * The unification plan's "Open" button uses this list to decide
 * whether an app's canonical URL can use the `/run/<slug>/` focused
 * shell route. Runtime iframes still load the underlying static bundle
 * with `?shippie_embed=1`.
 */
import { SHOWCASE_SLUGS } from '$lib/_generated/showcase-catalog';

const SLUG_ALIASES: Record<string, string> = {
  'recipe-saver': 'recipe',
};

export const FIRST_PARTY_SHOWCASE_SLUGS = new Set<string>(SHOWCASE_SLUGS);

export function isFirstPartyShowcase(slug: string): boolean {
  return FIRST_PARTY_SHOWCASE_SLUGS.has(canonicalShowcaseSlug(slug));
}

export function canonicalShowcaseSlug(slug: string): string {
  return SLUG_ALIASES[slug] ?? slug;
}

export function containerSlugForRequest(slug: string): string {
  // The curated container still uses recipe-saver as the app id/slug
  // because existing intent tests and permissions refer to that app.
  // /run/recipe remains the public runtime slug.
  if (slug === 'recipe') return 'recipe-saver';
  return slug;
}

export function canonicalAppUrl(slug: string): string {
  const canonical = canonicalShowcaseSlug(slug);
  return isFirstPartyShowcase(canonical)
    ? `/run/${encodeURIComponent(canonical)}/`
    : `https://${slug}.shippie.app/`;
}
