/**
 * First-party showcase slugs. Generated by `scripts/prepare-showcases.mjs`
 * so hooks, marketplace URLs, and offline precache share one source of
 * truth.
 *
 * The unification plan's "Open" button uses this list to decide
 * whether an app's canonical URL can use the `/run/<slug>/` focused
 * shell route. Runtime iframes still load the underlying static bundle
 * with `?shippie_embed=1`.
 */
import { SHOWCASE_SLUGS } from '$lib/_generated/showcase-catalog';

const SLUG_ALIASES: Record<string, string> = {
  'recipe-saver': 'recipe',
  // Phase 2 cleanup — legacy showcases consolidated into Move / Quiet /
  // Field Kitchen. Old install shortcuts and shared links resolve to the
  // consolidator so users don't 404 on stale URLs.
  pace: 'move',
  'sleep-logger': 'move',
  'workout-logger': 'move',
  pomodoro: 'quiet',
  'mood-pulse': 'quiet',
  coffee: 'field-kitchen',
  cooking: 'field-kitchen',
  dough: 'field-kitchen',
  'sip-log': 'field-kitchen',
  // daily-briefing demoted to platform-side `/today` surface (see
  // post-launch follow-up in plan). Until that lands, alias to recipe
  // — the most stable polished destination — so links don't 404.
  'daily-briefing': 'recipe',
};

export const FIRST_PARTY_SHOWCASE_SLUGS = new Set<string>(SHOWCASE_SLUGS);

export function isFirstPartyShowcase(slug: string): boolean {
  return FIRST_PARTY_SHOWCASE_SLUGS.has(canonicalShowcaseSlug(slug));
}

export function canonicalShowcaseSlug(slug: string): string {
  return SLUG_ALIASES[slug] ?? slug;
}

export function containerSlugForRequest(slug: string): string {
  return canonicalShowcaseSlug(slug);
}

export function canonicalAppUrl(slug: string): string {
  const canonical = canonicalShowcaseSlug(slug);
  return isFirstPartyShowcase(canonical)
    ? `/run/${encodeURIComponent(canonical)}/`
    : `https://${slug}.shippie.app/`;
}
