/**
 * GET /__shippie-pwa/sw.js
 *
 * Phase 9.1 — service worker for the marketplace itself. Distinct from
 * /__shippie/sw.js (which serves maker subdomains via the wrapper).
 *
 * Strategy:
 *   - cache-first only for immutable assets and raw showcase bundles
 *   - network-first for app shell documents, cached inside the current
 *     versioned SW cache so saved tools can still open offline
 *   - sealed offline capsules with a static launcher kernel for saved apps
 *   - graceful offline home that lists ready and repairable saved tools
 *
 * The browser caches it. Updates land naturally on next visit because the
 * body changes when we deploy.
 */
import type { RequestHandler } from './$types';
import { AI_RUNTIME_URLS } from '$lib/container/ai-runtime';
import { OFFLINE_CAPSULE_SW_HELPERS } from '@shippie/offline-capsule';
import LAUNCHER_HTML from '../../../../static/__shippie/launcher.html?raw';
import LAUNCHER_SCRIPT from '../../../../static/__shippie/launcher.js?raw';

const SW_BODY = `// shippie-marketplace SW
const CACHE = 'shippie-marketplace-__SHIPPIE_BUILD__';
const MODEL_CACHE = 'shippie.models.v1';
const CATALOG_PREFIX = '/tools';
const RUNTIME_PREFIX = '/__shippie-run';
// '/dock' is the front door; '/tools' is the catalog. '/' and
// '/container' remain so already-installed clients still resolve while
// they pick up the new shell.
const SHELL_DOCUMENTS = ['/dock', '/tools', '/you', '/', '/container'];
const KERNEL_HTML_URL = '/__shippie/launcher.html';
const KERNEL_HTML_ALIASES = [KERNEL_HTML_URL, '/__shippie/launcher'];
const KERNEL_SCRIPT_URL = '/__shippie/launcher.js';
const KERNEL_URLS = [...KERNEL_HTML_ALIASES, KERNEL_SCRIPT_URL];
const STATIC_LAUNCHER_HTML = __STATIC_LAUNCHER_HTML__;
const STATIC_LAUNCHER_SCRIPT = __STATIC_LAUNCHER_SCRIPT__;
__OFFLINE_CAPSULE_SW_HELPERS__
const DOWNLOAD_POINTER_STALE_MS = 2 * 60 * 1000;
// Phase 2: same-origin /__esm/<pkg> proxy serves the pinned
// Transformers runtime + its transitive graph through our own zone.
// The proxy rewrites every absolute import in the JS bodies back into
// the same /__esm/ namespace, so once we warm the entry URL the rest
// of the closure is also same-origin and cacheable here.
const AI_RUNTIME_URLS = __AI_RUNTIME_URLS__;
const AI_RUNTIME_PATH_PREFIX = '/__esm/';

// Branded offline response — used when network fails and there is no
// usable cached SvelteKit document. This is deliberately generated by
// the service worker, not by the app shell, so a top-level offline launch
// still gives users a useful saved-tools surface even if the platform
// route graph cannot hydrate.
const ROCKET_SVG = '<svg class="mark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" aria-hidden="true"><g transform="translate(0,10)"><path d="M512 180 L442 250 H582 Z" fill="#EDE4D3"/><rect x="440" y="260" width="64" height="64" fill="#3A4D35"/><rect x="520" y="260" width="64" height="64" fill="#E8603C"/><rect x="440" y="340" width="64" height="64" fill="#5E7B5C"/><rect x="520" y="340" width="64" height="64" fill="#A8C491"/><rect x="440" y="420" width="64" height="64" fill="#5E7B5C"/><rect x="520" y="420" width="64" height="64" fill="#A8C491"/><rect x="440" y="500" width="64" height="64" fill="#3A4D35"/><rect x="520" y="500" width="64" height="64" fill="#7A9A6E"/><rect x="440" y="580" width="64" height="64" fill="#7A9A6E"/><rect x="520" y="580" width="64" height="64" fill="#5E7B5C"/><path d="M356 516 L430 590 L430 676 L356 603 Z" fill="#5E7B5C"/><path d="M668 516 L594 590 L594 676 L668 603 Z" fill="#A8C491"/><path d="M512 652 C530 690 550 717 552 757 C537 742 522 746 512 780 C502 746 487 742 472 757 C474 717 494 690 512 652 Z" fill="#E8603C"/></g></svg>';

function escapeHtml(value) {
  return String(value || '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  })[char]);
}

function escapeAttr(value) {
  return escapeHtml(value);
}

function appLabelFromSlug(slug) {
  return String(slug || 'saved app')
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function titleFromHtml(html, slug) {
  const fallback = appLabelFromSlug(slug);
  const match = String(html || '').match(/<title[^>]*>([\\s\\S]*?)<\\/title>/i);
  const title = match
    ? match[1].replace(/<[^>]+>/g, '').replace(/\\s+/g, ' ').trim()
    : '';
  if (!title || /^(shippie|react app|vite \\+ react)/i.test(title)) return fallback;
  return title.replace(/\\s+[\\u2013\\u2014-]\\s+Shippie$/i, '').trim() || fallback;
}

function formatBytes(bytes) {
  if (!Number.isFinite(bytes) || bytes <= 0) return '';
  if (bytes < 1024 * 1024) return Math.max(1, Math.round(bytes / 1024)) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(bytes < 10 * 1024 * 1024 ? 1 : 0) + ' MB';
}

function staleDownloadPointer(pointer) {
  if (!pointer || pointer.state !== 'downloading') return false;
  const updated = Date.parse(pointer.updatedAt || '');
  return !Number.isFinite(updated) || Date.now() - updated > DOWNLOAD_POINTER_STALE_MS;
}

function iconUrlFromManifest(manifest) {
  const assets = Array.isArray(manifest && manifest.assets) ? manifest.assets : [];
  const icon = assets.find((asset) => {
    const url = typeof asset === 'string' ? asset : asset && asset.url;
    return typeof url === 'string' && /(?:^|\\/)(?:icon|favicon|apple-touch-icon)[^/]*\\.(?:svg|png|webp|jpg|jpeg)$/i.test(url);
  });
  return typeof icon === 'string' ? icon : icon && icon.url;
}

// Offline saved-tool links should open the dock shell focused route
// (/dock?app=<slug>&focused=1) so the in-tool switcher pull-tab exists,
// but only when the shell document is actually cached — otherwise the
// link would dead-end and the direct capsule launch is the better deal.
function dockFocusedHref(slug) {
  return '/dock?app=' + encodeURIComponent(slug) + '&focused=1';
}

async function dockShellAvailable(shellCache, slug) {
  if (!shellCache) return false;
  const keys = [absoluteUrl(dockFocusedHref(slug)), absoluteUrl('/dock')];
  for (const key of keys) {
    if (await shellCache.match(key)) return true;
  }
  return false;
}

async function offlineHomeApps(shellCache) {
  const pointers = await ShippieOfflineCapsule.listPointers().catch(() => []);
  const apps = [];
  for (const pointer of pointers) {
    if (!pointer || !pointer.slug) continue;
    if (pointer.state !== 'sealed') {
      if (pointer.state === 'partial' || pointer.state === 'evicted' || pointer.state === 'downloading') {
        apps.push({
          slug: pointer.slug,
          name: appLabelFromSlug(pointer.slug),
          ready: false,
          status: pointer.state === 'downloading' ? 'Save unfinished' : 'Needs refresh',
          totalBytes: pointer.totalBytes || 0,
          sealedAt: pointer.updatedAt || '',
        });
      }
      continue;
    }
    const manifest = await cachedCapsuleManifest(pointer);
    if (!manifest) {
      await ShippieOfflineCapsule.putPointer({ ...pointer, state: 'evicted', updatedAt: new Date().toISOString() }).catch(() => {});
      apps.push({
        slug: pointer.slug,
        name: appLabelFromSlug(pointer.slug),
        ready: false,
        status: 'Needs refresh',
        totalBytes: pointer.totalBytes || 0,
        sealedAt: pointer.sealedAt || pointer.updatedAt || '',
      });
      continue;
    }
    const cache = await caches.open(pointer.cacheName).catch(() => null);
    const entry = (cache ? await cache.match(pointer.entryUrl) : null) || responseFromAssetCopy(pointer, pointer.entryUrl);
    if (!entry) {
      await ShippieOfflineCapsule.putPointer({ ...pointer, state: 'evicted', updatedAt: new Date().toISOString() }).catch(() => {});
      apps.push({
        slug: pointer.slug,
        name: titleFromHtml('', pointer.slug),
        ready: false,
        status: 'Needs refresh',
        totalBytes: pointer.totalBytes || manifest.totalBytes || 0,
        sealedAt: pointer.sealedAt || pointer.updatedAt || '',
      });
      continue;
    }
    const html = await entry.clone().text().catch(() => '');
    apps.push({
      slug: pointer.slug,
      name: titleFromHtml(html, pointer.slug),
      ready: true,
      status: 'Ready offline',
      iconUrl: iconUrlFromManifest(manifest),
      totalBytes: pointer.totalBytes || manifest.totalBytes || 0,
      sealedAt: pointer.sealedAt || pointer.updatedAt || '',
      shellHref: (await dockShellAvailable(shellCache, pointer.slug)) ? dockFocusedHref(pointer.slug) : null,
    });
  }
  return apps.sort((a, b) => {
    const byDate = String(b.sealedAt || '').localeCompare(String(a.sealedAt || ''));
    return byDate || a.name.localeCompare(b.name);
  });
}

function offlineHomeHtml(apps) {
  const readyCount = apps.filter((app) => app.ready).length;
  const hasApps = apps.length > 0;
  const hasReadyApps = readyCount > 0;
  const count = readyCount === 1 ? '1 saved tool is' : readyCount + ' saved tools are';
  const appMarkup = hasApps
    ? '<section class="apps" aria-label="Saved tools">' + apps.map((app) => {
        const href = app.shellHref || ('/run/' + encodeURIComponent(app.slug) + '/');
        const bytes = formatBytes(app.totalBytes);
        const detail = app.ready ? (bytes || 'Ready offline') : (bytes ? app.status + ' · ' + bytes : app.status);
        const icon = app.iconUrl
          ? '<span class="icon"><img src="' + escapeAttr(app.iconUrl) + '" alt=""></span>'
          : '<span class="icon fallback">' + escapeHtml(app.name.slice(0, 1).toUpperCase()) + '</span>';
        const inner = icon + '<span class="copy"><strong>' + escapeHtml(app.name) + '</strong><small>' + escapeHtml(detail) + '</small></span>' + (app.ready ? '<span class="arrow" aria-hidden="true">&rsaquo;</span>' : '<span class="refresh" aria-hidden="true">Online</span>');
        return app.ready
          ? '<a class="app" href="' + escapeAttr(href) + '">' + inner + '</a>'
          : '<div class="app stale" aria-disabled="true">' + inner + '</div>';
      }).join('') + '</section>'
    : '<section class="empty"><strong>No saved tools on this device yet.</strong><span>Reconnect once, open a tool, and tap Save. After that it will launch from here without the network.</span></section>';
  const title = hasReadyApps ? 'Ready offline' : hasApps ? 'Saved tools need refresh' : 'You are offline';
  const body = hasReadyApps
    ? count + ' ready on this device. Pick up where you left off.'
    : hasApps
      ? 'Reconnect once and Shippie will re-seal these tools automatically.'
      : 'Reconnect to browse the marketplace.';
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Offline · Shippie</title><style>html{background:#14120f;color:#ede4d3;color-scheme:dark}body{margin:0;min-height:100vh;min-height:100dvh;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#14120f}main{box-sizing:border-box;min-height:100vh;min-height:100dvh;display:flex;flex-direction:column;gap:26px;padding:calc(28px + env(safe-area-inset-top)) 20px calc(28px + env(safe-area-inset-bottom));max-width:560px;margin:0 auto}.hero{display:flex;align-items:flex-start;gap:18px;padding-top:18vh}.mark{width:72px;height:72px;flex:0 0 auto}h1{font-size:2rem;line-height:1.05;margin:0 0 10px;font-weight:750;letter-spacing:0}p{font-size:1rem;line-height:1.45;color:#cbbba5;margin:0}.apps{display:grid;gap:10px}.app{display:flex;align-items:center;gap:14px;text-decoration:none;color:#ede4d3;background:#201d18;border:1px solid #3d352b;border-radius:16px;padding:13px 14px;min-height:62px;box-shadow:0 10px 32px rgba(0,0,0,.18)}.app:active{transform:translateY(1px);background:#28231d}.app.stale{opacity:.74}.icon{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:#2f392b;color:#ede4d3;overflow:hidden;flex:0 0 auto}.icon img{width:100%;height:100%;object-fit:cover}.icon.fallback{font-weight:800}.copy{display:grid;gap:4px;min-width:0;flex:1}.copy strong{font-size:1rem;line-height:1.15;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.copy small{font-size:.82rem;color:#a99984}.arrow{font-size:1.8rem;color:#a8c491;line-height:1}.refresh{font-size:.78rem;color:#d7c7ad;border:1px solid #514638;border-radius:999px;padding:5px 8px}.empty{display:grid;gap:8px;border:1px solid #3d352b;background:#201d18;border-radius:16px;padding:16px;line-height:1.4}.empty strong{font-size:1rem}.empty span{color:#b8a88f}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:auto}.button{appearance:none;border:1px solid #514638;border-radius:999px;background:#ede4d3;color:#14120f;text-decoration:none;font-weight:750;padding:11px 16px}.button.secondary{background:transparent;color:#ede4d3}small.status{color:#7f715d;font-size:.82rem}@media (max-width:430px){main{padding-left:18px;padding-right:18px}.hero{padding-top:16vh;display:grid;gap:16px}.mark{width:64px;height:64px}h1{font-size:1.8rem}}</style></head><body><main><section class="hero">' + ROCKET_SVG + '<div><h1>' + escapeHtml(title) + '</h1><p>' + escapeHtml(body) + '</p></div></section>' + appMarkup + '<div class="actions"><a class="button" href="/">Retry marketplace</a>' + (hasReadyApps ? '<a class="button secondary" href="/you">Saved tools</a>' : '') + '</div><small class="status">Shippie keeps sealed copies on this device. The marketplace will refresh when you are back online.</small></main></body></html>';
}

async function offlineResponse() {
  const shellCache = await caches.open(CACHE).catch(() => null);
  const apps = await offlineHomeApps(shellCache);
  return new Response(offlineHomeHtml(apps), {
    // A PWA navigation should never become the generic SvelteKit 500/503
    // error surface just because the device is briefly offline. This is a
    // real app state, so serve the branded offline launch surface as a
    // successful document.
    status: 200,
    headers: { 'content-type': 'text/html; charset=utf-8' },
  });
}

function expectedAssetResponse(req, res) {
  if (!res || !res.ok) return false;
  const path = new URL(req.url).pathname;
  const type = (res.headers.get('content-type') || '').toLowerCase();
  if (path.endsWith('.js') || path.endsWith('.mjs')) return type.includes('javascript') || type.includes('ecmascript');
  if (path.endsWith('.css')) return type.includes('text/css');
  if (path.endsWith('.wasm')) return type.includes('application/wasm');
  if (path.endsWith('.json')) return type.includes('json');
  if (path.endsWith('.svg')) return type.includes('image/svg');
  return !type.includes('text/html');
}

function expectedRuntimeResponse(req, res) {
  if (!res || !res.ok) return false;
  const url = new URL(req.url);
  const type = (res.headers.get('content-type') || '').toLowerCase();
  const isEntryDocument =
    url.pathname.endsWith('/') ||
    url.pathname.endsWith('/index.html') ||
    url.searchParams.get('shippie_embed') === '1';
  if (isEntryDocument) return type.includes('text/html');
  return expectedAssetResponse(req, res);
}

function expectedDocumentResponse(res) {
  if (!res || !res.ok) return false;
  return (res.headers.get('content-type') || '').toLowerCase().includes('text/html');
}

function browserReportsOffline() {
  return self.navigator && self.navigator.onLine === false;
}

// Slow-network budgets for network-first shell documents. With a saved
// copy in cache the network only gets a short head start before we serve
// the stale document; with nothing cached we wait much longer before
// surrendering to the offline surface.
const DOC_TIMEOUT_WITH_FALLBACK_MS = 3500;
const DOC_TIMEOUT_WITHOUT_FALLBACK_MS = 12000;

async function fetchWithTimeout(req, timeoutMs) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(req, { signal: controller.signal });
  } catch (err) {
    if (controller.signal.aborted) {
      const timedOut = new Error('document fetch exceeded ' + timeoutMs + 'ms');
      timedOut.name = 'ShippieSlowNetworkTimeout';
      throw timedOut;
    }
    throw err;
  } finally {
    clearTimeout(timer);
  }
}

// Tell every window that we just served a stale document because the
// network blew its budget — the shell flips its slow-network state and
// toasts once. Same broadcast shape as OFFLINE_CAPSULE_INCOMPLETE.
async function notifySlowNetworkFallback(resource) {
  try {
    if (!self.clients || !self.clients.matchAll) return;
    const wins = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of wins) client.postMessage({ type: 'SLOW_NETWORK_FALLBACK', resource });
  } catch {
    /* advisory only */
  }
}

function absoluteUrl(path) {
  return new URL(path, self.location.origin).toString();
}

function runSlugFromPath(path) {
  const match = path.match(/^\\/run\\/([^/]+)\\/?/);
  return match ? decodeURIComponent(match[1]) : null;
}

function runtimeSlugFromPath(path) {
  const match = path.match(/^\\/__shippie-run\\/([^/]+)(?:\\/|$)/);
  return match ? decodeURIComponent(match[1]) : null;
}

function capsuleManifestKey(slug, manifestHash) {
  return '/__shippie-capsules/' + encodeURIComponent(slug) + '/' + manifestHash + '.json';
}

function launcherUrlForSlug(slug) {
  return KERNEL_HTML_URL + (slug ? '?slug=' + encodeURIComponent(slug) : '');
}

function responseInit(res) {
  return { status: res.status, statusText: res.statusText, headers: new Headers(res.headers) };
}

function responseFromBytes(bytes, res) {
  return new Response(bytes.slice(0), responseInit(res));
}

async function navigationSafeResponse(res) {
  return responseFromBytes(await res.clone().arrayBuffer(), res);
}

function storedUrl(value) {
  const url = new URL(typeof value === 'string' ? value : value && value.url, self.location.origin);
  return url.origin === self.location.origin ? url.pathname + url.search : url.href;
}

function headersToPairs(headers) {
  return Array.from(headers.entries()).filter(([name]) => !/^(content-encoding|content-length|transfer-encoding)$/i.test(name));
}

function responseFromAssetCopy(pointer, value) {
  const key = storedUrl(value);
  const copies = Array.isArray(pointer && pointer.assetCopies) ? pointer.assetCopies : [];
  const copy = copies.find((item) => item && item.url === key);
  if (!copy || !copy.body) return null;
  const body = copy.body instanceof ArrayBuffer
    ? copy.body.slice(0)
    : ArrayBuffer.isView(copy.body)
      ? copy.body.buffer.slice(copy.body.byteOffset, copy.body.byteOffset + copy.body.byteLength)
      : null;
  if (!body) return null;
  return new Response(body, {
    status: copy.status || 200,
    statusText: copy.statusText || 'OK',
    headers: new Headers(Array.isArray(copy.headers) ? copy.headers : []),
  });
}

async function shadowCopiesFromCache(cache, manifest) {
  const copies = [];
  for (const asset of manifest.assets) {
    const hit = await cache.match(asset.url);
    if (!hit) continue;
    copies.push({
      url: asset.url,
      status: hit.status,
      statusText: hit.statusText,
      headers: headersToPairs(hit.headers),
      body: await hit.clone().arrayBuffer(),
    });
  }
  const manifestBody = new TextEncoder().encode(JSON.stringify(manifest)).buffer;
  copies.push({
    url: capsuleManifestKey(manifest.slug, manifest.manifestHash),
    status: 200,
    statusText: 'OK',
    headers: [['content-type', 'application/json']],
    body: manifestBody,
  });
  return copies;
}

async function shadowEntriesComplete(pointer, manifest) {
  let done = 0;
  const failed = [];
  for (const asset of manifest.assets) {
    const hit = responseFromAssetCopy(pointer, asset.url);
    if (!hit) {
      failed.push(asset.url);
      continue;
    }
    if (typeof asset.size === 'number') {
      const bytes = await hit.clone().arrayBuffer();
      if (bytes.byteLength !== asset.size) {
        failed.push(asset.url);
        continue;
      }
    }
    done += 1;
  }
  return { complete: failed.length === 0, done, total: manifest.assets.length, failed };
}

function inlineLauncherHtml() {
  const script = STATIC_LAUNCHER_SCRIPT.replace(/<\\/script/gi, '<\\\\/script');
  const inline = '<script>' + script + '</script>';
  return STATIC_LAUNCHER_HTML.replace('<script src="/__shippie/launcher.js"></script>', inline);
}

async function inlineLauncherResponse(slug) {
  if (!slug) return null;
  const pointer = await ShippieOfflineCapsule.getPointer(slug).catch(() => null);
  if (!pointer || pointer.state !== 'sealed') return null;
  const manifest = await cachedCapsuleManifest(pointer);
  if (!manifest) return null;
  const cache = pointer.cacheName ? await caches.open(pointer.cacheName).catch(() => null) : null;
  const entry =
    (cache ? await cache.match(pointer.entryUrl) : null) ||
    (cache ? await cache.match(manifest.entryUrl) : null) ||
    responseFromAssetCopy(pointer, pointer.entryUrl) ||
    responseFromAssetCopy(pointer, manifest.entryUrl);
  if (!entry) return null;
  return new Response(inlineLauncherHtml(), {
    status: 200,
    headers: { 'content-type': 'text/html; charset=utf-8' },
  });
}

function shellKeysForRequest(req) {
  const url = new URL(req.url);
  const keys = [url.toString()];
  if (url.pathname === '/') keys.push(absoluteUrl('/'));
  if (url.pathname === '/dock') keys.push(absoluteUrl('/dock'));
  if (url.pathname === '/container') keys.push(absoluteUrl('/container'));
  const slug = runSlugFromPath(url.pathname);
  if (slug) {
    keys.push(absoluteUrl('/run/' + encodeURIComponent(slug) + '/'));
    keys.push(absoluteUrl('/dock?app=' + encodeURIComponent(slug) + '&focused=1'));
    keys.push(absoluteUrl('/container?app=' + encodeURIComponent(slug) + '&focused=1'));
  }
  keys.push(absoluteUrl('/dock'));
  keys.push(absoluteUrl('/container'));
  keys.push(absoluteUrl('/'));
  return Array.from(new Set(keys));
}

function shellDocumentUrls(slug) {
  const urls = [...SHELL_DOCUMENTS];
  if (slug) {
    urls.push('/run/' + encodeURIComponent(slug) + '/');
    urls.push('/dock?app=' + encodeURIComponent(slug) + '&focused=1');
    urls.push('/container?app=' + encodeURIComponent(slug) + '&focused=1');
  }
  return urls.map(absoluteUrl);
}

async function cacheShellDocument(cache, req, res) {
  if (!expectedDocumentResponse(res)) return false;
  await cache.put(req, res.clone()).catch(() => {});
  const url = new URL(req.url);
  if (url.pathname === '/') {
    await cache.put(absoluteUrl('/'), res.clone()).catch(() => {});
  } else if (url.pathname === '/container' && !url.search) {
    await cache.put(absoluteUrl('/container'), res.clone()).catch(() => {});
  } else if (runSlugFromPath(url.pathname)) {
    await cache.put(absoluteUrl(url.pathname.endsWith('/') ? url.pathname : url.pathname + '/'), res.clone()).catch(() => {});
  }
  return true;
}

async function cachedShellDocument(cache, req) {
  for (const key of shellKeysForRequest(req)) {
    const hit = await cache.match(key);
    if (hit) return hit;
  }
  return null;
}

async function cachedRuntimeEntry(cache, slug) {
  if (!slug) return null;
  const pointer = await ShippieOfflineCapsule.getPointer(slug).catch(() => null);
  if (pointer && pointer.state === 'sealed' && pointer.cacheName && pointer.entryUrl) {
    const capsule = await caches.open(pointer.cacheName).catch(() => null);
    const hit = capsule ? await capsule.match(pointer.entryUrl) : null;
    if (hit) return hit;
    const shadow = responseFromAssetCopy(pointer, pointer.entryUrl);
    if (shadow) return shadow;
  }
  const encoded = encodeURIComponent(slug);
  const keys = [
    RUNTIME_PREFIX + '/' + encoded + '/?shippie_embed=1',
    RUNTIME_PREFIX + '/' + encoded + '/index.html',
    RUNTIME_PREFIX + '/' + encoded + '/',
  ];
  for (const key of keys) {
    const hit = await cache.match(key);
    if (hit) return hit;
  }
  return null;
}

async function cachedCapsuleResponse(req, slug) {
  if (!slug) return null;
  const pointer = await ShippieOfflineCapsule.getPointer(slug).catch(() => null);
  if (!pointer || pointer.state !== 'sealed' || !pointer.cacheName) return null;
  const capsule = await caches.open(pointer.cacheName).catch(() => null);
  const pathKey = new URL(req.url).pathname + new URL(req.url).search;
  if (capsule) {
    const cached = (await capsule.match(req)) || (await capsule.match(pathKey));
    if (cached) return cached;
  }
  return responseFromAssetCopy(pointer, pathKey);
}

async function cachedCapsuleManifest(pointer) {
  if (!pointer || !pointer.cacheName || !pointer.manifestHash || !pointer.slug) return null;
  const cache = await caches.open(pointer.cacheName).catch(() => null);
  if (cache) {
    const hit = await cache.match(capsuleManifestKey(pointer.slug, pointer.manifestHash));
    if (hit) {
      try {
        return await hit.json();
      } catch {
        /* fall through to the IDB pointer copy */
      }
    }
  }
  const fallback = pointer.manifest;
  if (
    fallback &&
    fallback.slug === pointer.slug &&
    fallback.manifestHash === pointer.manifestHash &&
    Array.isArray(fallback.assets)
  ) {
    return fallback;
  }
  return null;
}

async function warmKernel(cache) {
  for (const url of [KERNEL_HTML_URL, KERNEL_SCRIPT_URL]) {
    try {
      const req = new Request(url);
      const res = await fetch(req);
      const ok = url === KERNEL_HTML_URL ? expectedDocumentResponse(res) : expectedAssetResponse(req, res);
      if (!ok) continue;
      if (url === KERNEL_HTML_URL) {
        const bytes = await res.clone().arrayBuffer();
        await Promise.allSettled(
          KERNEL_HTML_ALIASES.map((alias) => cache.put(alias, responseFromBytes(bytes, res))),
        );
      } else {
        await cache.put(url, res.clone()).catch(() => {});
      }
    } catch {
      /* best effort — next online visit can repair the kernel */
    }
  }
}

async function cachedLauncher(cache, slug) {
  for (const alias of KERNEL_HTML_ALIASES) {
    const hit = await cache.match(alias);
    if (hit) return navigationSafeResponse(hit);
  }
  try {
    const res = await fetch(KERNEL_HTML_URL);
    if (expectedDocumentResponse(res)) {
      const bytes = await res.clone().arrayBuffer();
      await Promise.allSettled(
        KERNEL_HTML_ALIASES.map((alias) => cache.put(alias, responseFromBytes(bytes, res))),
      );
      return responseFromBytes(bytes, res);
    }
  } catch {
    /* fall through */
  }
  return (await inlineLauncherResponse(slug)) || cachedRuntimeEntry(cache, slug);
}

async function warmPlatformShell(cache, slug) {
  const urls = shellDocumentUrls(slug);
  let done = 0;
  for (const url of urls) {
    try {
      const req = new Request(url, { headers: { accept: 'text/html' } });
      const res = await fetch(req);
      if (await cacheShellDocument(cache, req, res)) done += 1;
    } catch {
      /* best effort — the next online navigation can warm this shell */
    }
  }
  return { done, total: urls.length };
}

async function checkShellComplete(cache, slug) {
  const urls = shellDocumentUrls(slug);
  let done = 0;
  for (const url of urls) {
    if (await cache.match(url)) done += 1;
  }
  return { complete: done === urls.length, done, total: urls.length };
}

async function purgeShellDocuments(cache) {
  const reqs = await cache.keys();
  await Promise.allSettled(
    reqs.map(async (req) => {
      const path = new URL(req.url).pathname;
      const keep =
        path.startsWith(RUNTIME_PREFIX + '/') ||
        path.startsWith('/_app/immutable/') ||
        path.startsWith('/__shippie/wasm/') ||
        KERNEL_URLS.includes(path) ||
        path.startsWith(AI_RUNTIME_PATH_PREFIX) ||
        path === '/__shippie-pwa/.shell-warmed';
      if (!keep) await cache.delete(req);
    }),
  );
}

async function warmAiRuntime(urls = AI_RUNTIME_URLS) {
  if (!Array.isArray(urls) || urls.length === 0) return;
  try {
    const cache = await caches.open(MODEL_CACHE);
    await Promise.allSettled(
      urls.map(async (url) => {
        const cached = await cache.match(url);
        if (cached) return;
        const res = await fetch(url);
        if (expectedAssetResponse(new Request(url), res)) await cache.put(url, res.clone()).catch(() => {});
      }),
    );
  } catch {
    /* best effort — first AI use can still fetch and cache the runtime */
  }
}

// Install stays intentionally tiny. Showcase runtimes cache on first
// open and sealed offline capsules cache only when the user taps Save.
// This keeps the PWA quick to activate and avoids hundreds of MB of
// surprise storage before the user has chosen which tools matter.
self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await warmKernel(cache);
    self.skipWaiting();
  })());
});

// ── Save-for-offline orchestration ───────────────────────────────────
// The page-side download utility posts MessageChannel-port messages to
// the active SW; the SW does all cache work and reports back via the
// port. This keeps the cache name (which is stamped here from
// CF_VERSION_METADATA) entirely internal — page code never has to guess.

async function cacheAddAll(cache, urls, onProgress) {
  // 3-at-a-time avoids hammering CF rate limits on bulk downloads.
  // Each fetch is best-effort; on failure the URL ends up in failed[].
  // We hand the response directly to cache.put without clone() because
  // the response body is not reused after — the previous clone roughly
  // doubled in-flight memory on big bundles.
  let done = 0;
  const total = urls.length;
  const failed = [];
  for (let i = 0; i < urls.length; i += 3) {
    const chunk = urls.slice(i, i + 3);
    await Promise.allSettled(chunk.map(async (url) => {
      try {
        const res = await fetch(url);
        const req = new Request(url);
        const shouldStore = url.startsWith(RUNTIME_PREFIX + '/')
          ? expectedRuntimeResponse(req, res)
          : expectedAssetResponse(req, res);
        if (shouldStore) {
          await cache.put(url, res).catch(() => {});
        } else {
          failed.push(url);
        }
      } catch {
        failed.push(url);
      } finally {
        done += 1;
        try { onProgress(done, total); } catch { /* progress is best-effort */ }
      }
    }));
  }
  return failed;
}

async function checkManifestComplete(cache, assets) {
  // Verify every URL in the manifest is in the cache. Catches partial
  // downloads where the network failed mid-way; saved-state should
  // never be claimed without this proof.
  let done = 0;
  for (const url of assets) {
    if (await cache.match(url)) done += 1;
  }
  return { complete: done === assets.length, done, total: assets.length };
}

async function warmShell(cache) {
  // First DOWNLOAD_APP per SW activation warms only shared, deploy-safe
  // runtime files. We intentionally do not cache SvelteKit route HTML
  // here: shell documents include current chunk hashes and are the main
  // source of random white screens after a deploy or hard PWA resume.
  const SENTINEL = '/__shippie-pwa/.shell-warmed';
  await warmKernel(cache);
  if (await cache.match(SENTINEL)) return;
  try {
    const res = await fetch('/__shippie-pwa/shell-assets.json');
    if (!res.ok) return;
    const shell = await res.json();
    const urls = [
      ...(Array.isArray(shell.wasm) ? shell.wasm : []),
    ];
    await cacheAddAll(cache, urls, () => {});
    await warmAiRuntime(Array.isArray(shell.aiRuntime) ? shell.aiRuntime : AI_RUNTIME_URLS);
    await cache.put(
      new Request(SENTINEL),
      new Response('1', { headers: { 'content-type': 'text/plain' } }),
    ).catch(() => {});
  } catch {
    /* best effort — shell will warm on next attempt */
  }
}

async function handleDownloadApp(slug, port) {
  try {
    const cache = await caches.open(CACHE);
    port.postMessage({ type: 'progress', phase: 'requested', slug, done: 0, total: 0 });
    const res = await fetch(RUNTIME_PREFIX + '/' + slug + '/__shippie-assets.json');
    if (!res.ok) throw new Error('manifest_fetch_failed_' + res.status);
    const manifest = await ShippieOfflineCapsule.sealManifest(await res.json(), self.location.origin);
    const capsuleCacheName = ShippieOfflineCapsule.cacheName(manifest.slug, manifest.manifestHash);
    const capsuleCache = await caches.open(capsuleCacheName);
      await ShippieOfflineCapsule.putPointer({
        slug: manifest.slug,
        manifestHash: manifest.manifestHash,
        cacheName: capsuleCacheName,
        entryUrl: manifest.entryUrl,
        state: 'downloading',
        totalBytes: manifest.totalBytes,
        manifest,
        updatedAt: new Date().toISOString(),
      });
    await warmShell(cache);
    await cacheAddAll(capsuleCache, manifest.assets.map((asset) => asset.url), (done, total) => {
      port.postMessage({ type: 'progress', phase: 'downloading', slug, done, total });
    });
    port.postMessage({ type: 'progress', phase: 'verifying', slug, done: manifest.assets.length, total: manifest.assets.length });
    const check = await ShippieOfflineCapsule.verifyCacheEntries(capsuleCache, manifest);
    const boot = check.complete
      ? await ShippieOfflineCapsule.syntheticBoot(capsuleCache, manifest)
      : { ok: false, missing: [], external: [] };
    if (check.complete && boot.ok) {
      await capsuleCache.put(
        capsuleManifestKey(manifest.slug, manifest.manifestHash),
        new Response(JSON.stringify(manifest), { headers: { 'content-type': 'application/json' } }),
      ).catch(() => {});
      const assetCopies = await shadowCopiesFromCache(capsuleCache, manifest).catch(() => []);
      await ShippieOfflineCapsule.putPointer({
        slug: manifest.slug,
        manifestHash: manifest.manifestHash,
        cacheName: capsuleCacheName,
        entryUrl: manifest.entryUrl,
        state: 'sealed',
        totalBytes: manifest.totalBytes,
        manifest,
        assetCopies,
        sealedAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
      port.postMessage({
        type: 'done',
        phase: 'sealed',
        state: 'saved',
        slug,
        total: check.total,
        totalBytes: manifest.totalBytes,
        manifestHash: manifest.manifestHash,
      });
    } else {
      const failed = [
        ...(Array.isArray(check.failed) ? check.failed : []),
        ...(Array.isArray(boot.missing) ? boot.missing : []),
        ...(Array.isArray(boot.external) ? boot.external : []),
      ];
      await ShippieOfflineCapsule.putPointer({
        slug: manifest.slug,
        manifestHash: manifest.manifestHash,
        cacheName: capsuleCacheName,
        entryUrl: manifest.entryUrl,
        state: 'partial',
        totalBytes: manifest.totalBytes,
        manifest,
        error: failed.slice(0, 5).join(', '),
        updatedAt: new Date().toISOString(),
      });
      port.postMessage({
        type: 'done', state: 'partial', slug,
        done: check.done, total: check.total,
        totalBytes: manifest.totalBytes,
        failedUrls: failed,
      });
    }
  } catch (err) {
    const error = String(err && err.message || err);
    const pointer = await ShippieOfflineCapsule.getPointer(slug).catch(() => null);
    if (pointer && pointer.state === 'downloading') {
      await ShippieOfflineCapsule.putPointer({
        ...pointer,
        state: 'error',
        error,
        updatedAt: new Date().toISOString(),
      }).catch(() => {});
    }
    port.postMessage({ type: 'done', state: 'error', slug, error });
  }
}

async function handleRemoveApp(slug, port) {
  try {
    const cache = await caches.open(CACHE);
    const reqs = await cache.keys();
    const runtimePrefix = RUNTIME_PREFIX + '/' + slug + '/';
    const shellPrefix = '/run/' + slug + '/';
    let count = 0;
    const names = await caches.keys();
    await Promise.allSettled(
      names
        .filter((name) => name.startsWith('capsule:' + slug + ':'))
        .map(async (name) => {
          if (await caches.delete(name)) count += 1;
        }),
    );
    await ShippieOfflineCapsule.deletePointer(slug).catch(() => {});
    for (const req of reqs) {
      const path = new URL(req.url).pathname;
      if (path.startsWith(runtimePrefix) || path.startsWith(shellPrefix)) {
        await cache.delete(req);
        count += 1;
      }
    }
    port.postMessage({ type: 'done', state: 'removed', slug, count });
  } catch (err) {
    port.postMessage({ type: 'done', state: 'error', slug, error: String(err && err.message || err) });
  }
}

async function handleGetStatus(slug, port) {
  try {
    const pointer = await ShippieOfflineCapsule.getPointer(slug).catch(() => null);
    if (pointer && pointer.state === 'sealed') {
      const manifest = await cachedCapsuleManifest(pointer);
      if (manifest) {
        const cache = await caches.open(pointer.cacheName).catch(() => null);
        const cacheCheck = cache
          ? await ShippieOfflineCapsule.verifyCacheEntries(cache, manifest)
          : { complete: false, done: 0, total: manifest.assets.length, failed: manifest.assets.map((asset) => asset.url) };
        const shadowCheck = cacheCheck.complete ? cacheCheck : await shadowEntriesComplete(pointer, manifest);
        const check = cacheCheck.complete ? cacheCheck : shadowCheck;
        const state = check.complete ? 'saved' : 'partial';
        if (!check.complete) {
          await ShippieOfflineCapsule.putPointer({ ...pointer, state: 'evicted', updatedAt: new Date().toISOString() }).catch(() => {});
        }
        port.postMessage({
          type: 'status',
          slug,
          state,
          phase: check.complete ? 'sealed' : 'evicted',
          done: check.done,
          total: check.total,
          totalBytes: pointer.totalBytes || manifest.totalBytes || 0,
          manifestHash: pointer.manifestHash,
        });
        return;
      }
      await ShippieOfflineCapsule.putPointer({ ...pointer, state: 'evicted', updatedAt: new Date().toISOString() }).catch(() => {});
      port.postMessage({
        type: 'status',
        slug,
        state: 'partial',
        phase: 'evicted',
        done: 0,
        total: 0,
        totalBytes: pointer.totalBytes || 0,
        manifestHash: pointer.manifestHash,
      });
      return;
    }
    if (pointer && (pointer.state === 'error' || staleDownloadPointer(pointer))) {
      if (staleDownloadPointer(pointer)) {
        await ShippieOfflineCapsule.putPointer({
          ...pointer,
          state: 'error',
          error: pointer.error || 'download_interrupted',
          updatedAt: new Date().toISOString(),
        }).catch(() => {});
      }
      port.postMessage({
        type: 'status',
        slug,
        state: 'error',
        phase: 'error',
        done: 0,
        total: 0,
        totalBytes: pointer.totalBytes || 0,
        manifestHash: pointer.manifestHash,
        error: pointer.error || 'download_interrupted',
      });
      return;
    }
    if (pointer && (pointer.state === 'downloading' || pointer.state === 'partial' || pointer.state === 'evicted')) {
      port.postMessage({
        type: 'status',
        slug,
        state: 'partial',
        phase: pointer.state,
        done: 0,
        total: 0,
        totalBytes: pointer.totalBytes || 0,
        manifestHash: pointer.manifestHash,
      });
      return;
    }
    port.postMessage({ type: 'status', slug, state: 'idle', phase: 'idle', done: 0, total: 0 });
  } catch {
    port.postMessage({ type: 'status', slug, state: 'idle', done: 0, total: 0 });
  }
}

async function handleListSavedApps(port) {
  try {
    const pointers = await ShippieOfflineCapsule.listPointers().catch(() => []);
    // Pointer integrity checks are independent; run them concurrently so
    // a saved-tools list of 15+ apps doesn't take seconds to assemble on
    // /you and SavedDock mount. Return unhealthy pointers too: hiding a
    // partial or evicted capsule makes "saved" feel dishonest.
    const results = await Promise.all(
      pointers.filter(Boolean).map(async (pointer) => {
        const base = {
          slug: pointer.slug,
          totalBytes: pointer.totalBytes || 0,
          manifestHash: pointer.manifestHash,
          sealedAt: pointer.sealedAt,
          updatedAt: pointer.updatedAt,
          error: pointer.error,
        };
        if (pointer.state !== 'sealed') {
          const staleDownload = staleDownloadPointer(pointer);
          if (staleDownload) {
            await ShippieOfflineCapsule.putPointer({
              ...pointer,
              state: 'error',
              error: pointer.error || 'download_interrupted',
              updatedAt: new Date().toISOString(),
            }).catch(() => {});
          }
          return {
            ...base,
            state:
              staleDownload
                ? 'error'
                : pointer.state === 'downloading'
                ? 'downloading'
                : pointer.state === 'evicted'
                  ? 'evicted'
                  : pointer.state === 'error'
                    ? 'error'
                    : 'partial',
            phase: pointer.state || 'partial',
          };
        }
        const manifest = await cachedCapsuleManifest(pointer);
        if (!manifest) {
          await ShippieOfflineCapsule.putPointer({ ...pointer, state: 'evicted', updatedAt: new Date().toISOString() }).catch(() => {});
          return { ...base, state: 'evicted', phase: 'evicted' };
        }
        const cache = await caches.open(pointer.cacheName).catch(() => null);
        const entry = (cache ? await cache.match(pointer.entryUrl) : null) || responseFromAssetCopy(pointer, pointer.entryUrl);
        if (!entry) {
          await ShippieOfflineCapsule.putPointer({ ...pointer, state: 'evicted', updatedAt: new Date().toISOString() }).catch(() => {});
          return { ...base, state: 'evicted', phase: 'evicted', totalBytes: pointer.totalBytes || manifest.totalBytes || 0 };
        }
        return {
          ...base,
          state: 'saved',
          phase: 'sealed',
          totalBytes: pointer.totalBytes || manifest.totalBytes || 0,
        };
      }),
    );
    const apps = results.filter(Boolean).sort((a, b) => a.slug.localeCompare(b.slug));
    port.postMessage({ type: 'saved-apps', slugs: apps.filter((app) => app.state === 'saved').map((app) => app.slug), apps });
  } catch (err) {
    port.postMessage({ type: 'saved-apps', slugs: [], error: String(err && err.message || err) });
  }
}

async function handleClearOffline(port) {
  // Delete user-saved app bundles only. Keep deploy-safe platform assets:
  // /_app/immutable/* (chunks), /__shippie/wasm/* (shared WASM),
  // /__shippie-pwa/* (sentinel + shell-assets manifest).
  try {
    const cache = await caches.open(CACHE);
    const reqs = await cache.keys();
    let count = 0;
    const pointers = await ShippieOfflineCapsule.listPointers().catch(() => []);
    for (const pointer of pointers) {
      if (pointer && pointer.slug) await ShippieOfflineCapsule.deletePointer(pointer.slug).catch(() => {});
    }
    const names = await caches.keys();
    await Promise.allSettled(
      names
        .filter((name) => name.startsWith('capsule:'))
        .map(async (name) => {
          if (await caches.delete(name)) count += 1;
        }),
    );
    for (const req of reqs) {
      const path = new URL(req.url).pathname;
      if (path.startsWith(RUNTIME_PREFIX + '/')) {
        await cache.delete(req);
        count += 1;
      }
    }
    port.postMessage({ type: 'done', state: 'cleared', count });
  } catch (err) {
    port.postMessage({ type: 'done', state: 'error', error: String(err && err.message || err) });
  }
}

self.addEventListener('message', (e) => {
  // Skip-waiting trigger from the page shell. Updates are applied
  // silently; controllerchange reloads the document once the worker
  // claims the page.
  if (e.data === 'SKIP_WAITING' || (e.data && e.data.type === 'SKIP_WAITING')) {
    self.skipWaiting();
    return;
  }
  // Version probe — kept for diagnostics and older clients. Replies via
  // the MessageChannel port if provided; otherwise via the message source.
  if (e.data && e.data.t === 'version') {
    const port = e.ports && e.ports[0];
    const reply = { versionId: '__SHIPPIE_BUILD__' };
    if (port) port.postMessage(reply);
    else if (e.source && 'postMessage' in e.source) e.source.postMessage(reply);
    return;
  }
  // Save-for-offline messages always carry a MessageChannel port so
  // the SW can stream progress + a final state.
  const port = e.ports && e.ports[0];
  if (!port) return;
  const msg = e.data || {};
  if (msg.type === 'DOWNLOAD_APP' && typeof msg.slug === 'string') {
    handleDownloadApp(msg.slug, port);
  } else if (msg.type === 'REMOVE_APP' && typeof msg.slug === 'string') {
    handleRemoveApp(msg.slug, port);
  } else if (msg.type === 'GET_APP_STATUS' && typeof msg.slug === 'string') {
    handleGetStatus(msg.slug, port);
  } else if (msg.type === 'LIST_SAVED_APPS') {
    handleListSavedApps(port);
  } else if (msg.type === 'CLEAR_OFFLINE') {
    handleClearOffline(port);
  } else {
    port.postMessage({ type: 'done', state: 'error', error: 'unknown_message' });
  }
});

// Migrate-then-delete: when a new versioned SW activates, copy ONLY
// content-addressed entries (/_app/immutable/* and /__shippie-run/* assets) from any
// prior 'shippie-marketplace-*' cache into the new cache, then delete
// the old caches.
//
// Why selective: platform HTML pages (/, /apps, /apps/<slug>) reference
// the current deploy's chunk hashes inside their <script> tags. After a
// deploy, those hashes change. A migrated stale HTML page references
// hashes that 404 on the server — SvelteKit's client tries to load
// them, fails, and +error.svelte fires ("Something went wrong" while
// browsing).
//
// /__shippie-run/<slug>/?shippie_embed=1 and nested app assets are
// self-consistent — the showcase HTML and its hashed chunks build together,
// so caching the bundle is safe across platform deploys. The bare /run/<slug>/
// route is platform shell HTML and must not migrate across deploys.
//
// Stale platform HTML is never warmed or migrated. If a prior worker
// already cached it under the current cache name, purge it on activation.
self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const newCache = await caches.open(CACHE);
    const oldNames = (await caches.keys()).filter(
      (n) => n !== CACHE && n.startsWith('shippie-marketplace-'),
    );
    for (const name of oldNames) {
      try {
        const old = await caches.open(name);
        const reqs = await old.keys();
        await Promise.allSettled(
          reqs.map(async (req) => {
            const path = new URL(req.url).pathname;
            const safeToMigrate =
              path.startsWith('/_app/immutable/') ||
              path.startsWith('/__shippie/wasm/');
            if (!safeToMigrate) return;
            const hit = await old.match(req);
            if (hit) await newCache.put(req, hit).catch(() => {});
          }),
        );
      } catch {
        /* best effort */
      }
      await caches.delete(name);
    }
    await purgeShellDocuments(newCache);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // AI runtime — same-origin /__esm/* proxy. Cache-first against the
  // dedicated MODEL_CACHE because the proxy serves immutable artifacts
  // (pinned versions, content-addressed transitive paths) and this
  // cache survives platform deploys via its separate name. Covers both
  // the entry URLs from AI_RUNTIME_URLS and any rewritten transitive
  // import the runtime pulls in at parse time.
  if (
    url.origin === self.location.origin &&
    url.pathname.startsWith(AI_RUNTIME_PATH_PREFIX)
  ) {
    e.respondWith((async () => {
      const cache = await caches.open(MODEL_CACHE);
      const cached = await cache.match(req);
      if (cached) return cached;
      try {
        const res = await fetch(req);
        if (expectedAssetResponse(req, res)) cache.put(req, res.clone()).catch(() => {});
        return res;
      } catch {
        return new Response('', { status: 504 });
      }
    })());
    return;
  }

  // Only same-origin marketplace traffic.
  if (url.origin !== self.location.origin) return;

  // Skip /__shippie-pwa/* (this SW + manifest icons) — let them go straight.
  if (url.pathname.startsWith('/__shippie-pwa/')) return;
  // Skip auth + deploy flows — these need fresh data.
  if (url.pathname.startsWith('/auth/')) return;
  if (url.pathname.startsWith('/api/')) return;
  if (url.pathname.startsWith('/dashboard/')) return;
  if (url.pathname.startsWith('/maker/')) return;
  if (url.pathname.startsWith('/admin/')) return;

  // Standalone post-cloud kernel. These two static files must survive
  // even when the SvelteKit shell cannot resolve its route/chunk graph.
  if (KERNEL_URLS.includes(url.pathname)) {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      if (KERNEL_HTML_ALIASES.includes(url.pathname)) {
        const cached = await cachedLauncher(cache);
        if (cached) return cached;
        return offlineResponse();
      }
      const cached = await cache.match(KERNEL_SCRIPT_URL);
      if (cached) return cached;
      try {
        const res = await fetch(req);
        const ok = expectedAssetResponse(req, res);
        if (ok) cache.put(KERNEL_SCRIPT_URL, res.clone()).catch(() => {});
        return res;
      } catch {
        return new Response('', { status: 504 });
      }
    })());
    return;
  }

  // /_app/immutable/* — SvelteKit's hashed JS + CSS chunks. Different
  // deploys produce different hashes (= different URLs), so cache-first
  // is safe: a cached hit always matches its content. Without this
  // handler, iOS PWAs lose JS chunks under storage pressure and pages
  // stop hydrating offline — the page looks like only the boot loader
  // rendered (rocket forever, no marketplace). 504 fallback when cache
  // miss + offline; modern SvelteKit's import-on-demand makes that
  // rare once entry chunks are warm.
  if (url.pathname.startsWith('/_app/immutable/')) {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(req);
      if (cached) return cached;
      try {
        const res = await fetch(req);
        if (expectedAssetResponse(req, res)) cache.put(req, res.clone()).catch(() => {});
        return res;
      } catch {
        return new Response('', { status: 504 });
      }
    })());
    return;
  }

  // /__shippie-run/<slug>/* — network-first for entry documents while
  // online, cache-first for hashed runtime assets, and sealed capsules
  // only as offline fallback. Saved/offline should never pin an online
  // user to an old app bundle after a deploy.
  if (url.pathname.startsWith(RUNTIME_PREFIX + '/')) {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const slug = runtimeSlugFromPath(url.pathname);
      const isEntryDocument = ShippieOfflineCapsule.isDocumentRequest(req);
      const capsuleHit = async () => cachedCapsuleResponse(req, slug);

      if (isEntryDocument && !browserReportsOffline()) {
        try {
          const res = await fetch(req);
          if (expectedRuntimeResponse(req, res)) {
            cache.put(req, res.clone()).catch(() => {});
            return res;
          }
        } catch {
          /* fall through to cache/capsule fallback */
        }
      }

      if (browserReportsOffline()) {
        const offlineHit = await capsuleHit();
        if (offlineHit) return offlineHit;
      }

      const cached = await cache.match(req);
      if (cached) {
        if (!expectedRuntimeResponse(req, cached)) {
          await cache.delete(req).catch(() => {});
        } else {
        // Refresh in background. Only keep complete app package entries
        // or typed assets, never accidental HTML error documents.
        fetch(req).then((res) => {
          if (expectedRuntimeResponse(req, res)) cache.put(req, res.clone()).catch(() => {});
        }).catch(() => {});
        return cached;
        }
      }
      try {
        const res = await fetch(req);
        if (expectedRuntimeResponse(req, res)) {
          cache.put(req, res.clone()).catch(() => {});
        } else if (!ShippieOfflineCapsule.isDocumentRequest(req)) {
          return ShippieOfflineCapsule.repairResponse(slug || 'unknown', url.pathname);
        }
        return res;
      } catch {
        const offlineHit = await capsuleHit();
        if (offlineHit) return offlineHit;
        if (isEntryDocument) {
          const launcher = await cachedLauncher(cache, slug);
          if (launcher) return launcher;
        }
        return ShippieOfflineCapsule.repairResponse(slug || 'unknown', url.pathname);
      }
    })());
    return;
  }

  // /run/<slug>/ — public focused shell. Network-only for route HTML so
  // hashed SvelteKit chunks stay fresh; offline gets the branded shell
  // instead of a stale route document.
  if (url.pathname.startsWith('/run/')) {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const slug = runSlugFromPath(url.pathname);
      if (browserReportsOffline()) {
        return (await cachedLauncher(cache, slug)) || offlineResponse();
      }
      try {
        const res = await fetch(req);
        if (expectedDocumentResponse(res)) cacheShellDocument(cache, req, res.clone()).catch(() => {});
        return res;
      } catch {
        return (
          (await cachedLauncher(cache, slug)) ||
          offlineResponse()
        );
      }
    })());
    return;
  }

  if (url.pathname.startsWith(CATALOG_PREFIX)) {
    // Catalog route (/tools). Route HTML is network-first + shell-cached;
    // app assets are handled by the immutable/runtime branches above.
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      if (browserReportsOffline()) return offlineResponse();
      try {
        const res = await fetch(req);
        if (expectedDocumentResponse(res)) cacheShellDocument(cache, req, res.clone()).catch(() => {});
        return res;
      } catch {
        return (await cachedShellDocument(cache, req)) || offlineResponse();
      }
    })());
    return;
  }

  // Network-first elsewhere for route documents. Do not cache these in
  // Cache API; SvelteKit HTML is deploy-coupled to current chunk hashes.
  const isDoc = req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html');
  if (isDoc) {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      if (browserReportsOffline()) {
        // Offline-home saved-tool links open /dock?app=<slug>&focused=1 so
        // the in-tool switcher exists. Serve the cached dock shell for those
        // instead of bouncing back to the offline home. The query string is
        // handled by shellKeysForRequest (exact match first, then /dock).
        if (url.pathname === '/dock' && url.searchParams.get('app')) {
          const cachedDock = await cachedShellDocument(cache, req);
          if (cachedDock) return cachedDock;
        }
        return offlineResponse();
      }
      // Network-first with a slow-network budget: a saved copy in cache
      // means the network only gets ~3.5s before we serve the stale doc;
      // no copy means we wait longer before the offline surface.
      const cachedDoc = await cachedShellDocument(cache, req);
      const budgetMs = cachedDoc ? DOC_TIMEOUT_WITH_FALLBACK_MS : DOC_TIMEOUT_WITHOUT_FALLBACK_MS;
      try {
        const res = await fetchWithTimeout(req, budgetMs);
        if (expectedDocumentResponse(res)) cacheShellDocument(cache, req, res.clone()).catch(() => {});
        return res;
      } catch (err) {
        if (cachedDoc) {
          if (err && err.name === 'ShippieSlowNetworkTimeout') notifySlowNetworkFallback(url.pathname);
          return cachedDoc;
        }
        return offlineResponse();
      }
    })());
  }
});
`;

export const GET: RequestHandler = async ({ platform }) => {
  // Stamp the cache name with the deployment version ID so old caches
  // drop on activate when the worker version changes. Falls back to
  // 'dev' locally where the binding doesn't exist; the literal makes
  // every dev session share one cache, which matches dev expectations.
  const buildId =
    (platform?.env as { CF_VERSION_METADATA?: { id?: string } } | undefined)?.CF_VERSION_METADATA?.id ?? 'dev';
  const body = SW_BODY
    .replace(/__SHIPPIE_BUILD__/g, buildId)
    .replace('__STATIC_LAUNCHER_HTML__', JSON.stringify(LAUNCHER_HTML))
    .replace('__STATIC_LAUNCHER_SCRIPT__', JSON.stringify(LAUNCHER_SCRIPT))
    .replace('__OFFLINE_CAPSULE_SW_HELPERS__', OFFLINE_CAPSULE_SW_HELPERS)
    .replace('__AI_RUNTIME_URLS__', JSON.stringify(AI_RUNTIME_URLS));
  return new Response(body, {
    status: 200,
    headers: {
      'content-type': 'application/javascript; charset=utf-8',
      'service-worker-allowed': '/',
      'cache-control': 'no-store',
    },
  });
};
