import {
  boolean,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';
import { apps } from './apps.ts';
import { deploys } from './deploys.ts';
import { users } from './users.ts';

/**
 * Compliance check results. Status includes 'needs_action' (Fix v5.1.3 M).
 *
 * Spec v6 §14.4.
 */
export const complianceChecks = pgTable(
  'compliance_checks',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    appId: uuid('app_id')
      .notNull()
      .references(() => apps.id, { onDelete: 'cascade' }),
    platform: text('platform').notNull(), // 'ios' | 'android' | 'both' | 'web'
    checkType: text('check_type').notNull(),
    status: text('status').notNull(),
    // 'passed' | 'failed' | 'pending' | 'not_applicable' | 'needs_action'
    evidence: jsonb('evidence'),
    checkedAt: timestamp('checked_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index('compliance_checks_app_platform_idx').on(t.appId, t.platform),
    index('compliance_checks_app_type_idx').on(t.appId, t.checkType),
  ],
);
export type ComplianceCheckRow = typeof complianceChecks.$inferSelect;
export type NewComplianceCheckRow = typeof complianceChecks.$inferInsert;

/**
 * iOS Privacy Manifest + Android Data Safety source of truth.
 * Generated by the compliance runner from static analysis of SDK usage
 * and function outbound calls.
 *
 * Spec v6 §14.1.
 */
export const privacyManifests = pgTable(
  'privacy_manifests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    appId: uuid('app_id')
      .notNull()
      .references(() => apps.id, { onDelete: 'cascade' }),
    deployId: uuid('deploy_id').references(() => deploys.id, { onDelete: 'set null' }),
    collectedData: jsonb('collected_data').notNull(),
    accessedApis: jsonb('accessed_apis').notNull(),
    trackingEnabled: boolean('tracking_enabled').default(false).notNull(),
    trackingDomains: text('tracking_domains').array(),
    dataSafetyAndroid: jsonb('data_safety_android').notNull(),
    generatedAt: timestamp('generated_at', { withTimezone: true }).defaultNow().notNull(),
    source: text('source'),
  },
  (t) => [index('privacy_manifests_app_idx').on(t.appId, t.generatedAt)],
);
export type PrivacyManifest = typeof privacyManifests.$inferSelect;

/**
 * Per-user account deletion requests with 14-day grace period.
 * Populated ONLY when an app retains user data (see Fix v5.1.2 I).
 */
export const accountDeletionRequests = pgTable(
  'account_deletion_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    appId: uuid('app_id')
      .notNull()
      .references(() => apps.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    requestedAt: timestamp('requested_at', { withTimezone: true }).defaultNow().notNull(),
    gracePeriodEndsAt: timestamp('grace_period_ends_at', { withTimezone: true }).notNull(),
    confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
    executedAt: timestamp('executed_at', { withTimezone: true }),
    cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
  },
  (t) => [unique('account_deletion_unique').on(t.appId, t.userId)],
);
export type AccountDeletionRequest = typeof accountDeletionRequests.$inferSelect;
