// Generated by scripts/prepare-showcases.mjs.
// Compatibility re-export for older imports; the generated showcase
// catalog is the single source of truth.
export { SHOWCASE_PRECACHE } from './showcase-catalog';
