// Generated by scripts/prepare-showcases.mjs.
// Re-run `bun scripts/prepare-showcases.mjs` (or `bun run build`)
// to refresh from the showcase set under apps/showcase-*.

export const SHOWCASE_SLUGS = [
  "atlas",
  "body-metrics",
  "breath",
  "co-pilot",
  "coffee",
  "cooking",
  "crewtrip",
  "cycle",
  "dough",
  "habit-tracker",
  "hearth",
  "journal",
  "ledger",
  "live-room",
  "matchday",
  "meal-planner",
  "mevrouw",
  "move",
  "pantry-scanner",
  "quiet",
  "read-later",
  "receipt-snap",
  "recipe",
  "restaurant-memory",
  "shopping-list",
  "show-and-tell",
  "sip-log",
  "story-studio",
  "symptom-diary",
  "therapy-notes",
  "whiteboard"
] as const;

export const SHOWCASE_PRECACHE: readonly string[] = SHOWCASE_SLUGS.flatMap((slug) => [
  `/run/${slug}/`,
  `/run/${slug}/index.html`,
]);
