// Generated by scripts/prepare-showcases.mjs.
// Re-run `bun scripts/prepare-showcases.mjs` (or `bun run build`)
// to refresh from the showcase set under apps/showcase-*.

export const SHOWCASE_SLUGS = [] as const;

export const SHOWCASE_PRECACHE: readonly string[] = SHOWCASE_SLUGS.map((slug) => `/__shippie-run/${slug}/?shippie_embed=1`);
