// Generated by scripts/prepare-showcases.mjs.
// Re-run `bun scripts/prepare-showcases.mjs` (or `bun run build`)
// to refresh from the showcase set under apps/showcase-*.

export const SHOWCASE_SLUGS = [
  "body-metrics",
  "breath",
  "coffee",
  "cooking",
  "daily-briefing",
  "dough",
  "habit-tracker",
  "journal",
  "live-room",
  "meal-planner",
  "mevrouw",
  "mood-pulse",
  "pace",
  "pantry-scanner",
  "pomodoro",
  "read-later",
  "recipe",
  "restaurant-memory",
  "shopping-list",
  "show-and-tell",
  "sip-log",
  "sleep-logger",
  "whiteboard",
  "workout-logger"
] as const;

export const SHOWCASE_PRECACHE: readonly string[] = SHOWCASE_SLUGS.flatMap((slug) => [
  `/run/${slug}/`,
  `/run/${slug}/index.html`,
]);
