/**
 * CSP header builder for static deploys.
 *
 * Trimmed port of apps/web/lib/trust/csp-builder.ts. Generates a CSP
 * header line + a meta tag that gets injected into every HTML file.
 *
 * Rules:
 *   - default-src 'self'
 *   - script-src  'self' 'unsafe-inline' (for hashed bundles + inline boot)
 *   - style-src   'self' 'unsafe-inline'
 *   - connect-src 'self' + declared/detected safe feature domains
 *   - img-src     'self' data: blob: + detected image hosts
 *   - frame-src   'self' + detected frame hosts
 */

import type { ShippieJsonLite } from './manifest';
import type { ConnectionGuardCspPolicy } from '@shippie/analyse';

/**
 * Framing policy for maker app runtime responses. Apps are framed
 * cross-origin by the Shippie Dock (apex/canary platform hosts), so
 * frame-ancestors must permit those origins — but NOT a wildcard
 * `*.shippie.app`, which would let one maker app frame another
 * (clickjacking). Shared by buildCsp (static), the wrapper finalizer,
 * and the wrapped-app CSP builder so all three agree.
 */
export const PLATFORM_FRAME_ANCESTORS =
  "'self' https://shippie.app https://www.shippie.app https://next.shippie.app";

export interface CspResult {
  /** Full HTTP header value, e.g. "default-src 'self'; ..." */
  header: string;
  /** Inline `<meta http-equiv="Content-Security-Policy">` element. */
  metaTag: string;
}

export interface BuildCspOptions {
  /**
   * Generated by Connection Guard. These domains are derived from the actual
   * uploaded bundle and become the runtime allowlist.
   */
  policy?: Partial<ConnectionGuardCspPolicy>;
  /**
   * Additional connect domains already approved by Local Tool policy or the
   * maker manifest. Kept separate so older callers can still use buildCsp
   * without constructing a full Connection Guard policy.
   */
  connectDomains?: readonly string[];
}

export function buildCsp(manifest: ShippieJsonLite, opts: BuildCspOptions = {}): CspResult {
  const externalAllowed = manifest.permissions?.external_network === true;
  const connectDomains = uniqueSources([
    ...(externalAllowed ? manifest.allowed_connect_domains ?? [] : []),
    ...(opts.connectDomains ?? []),
    ...(opts.policy?.connectSrc ?? []),
  ]);
  const styleDomains = uniqueSources(opts.policy?.styleSrc ?? []);
  const fontDomains = uniqueSources(opts.policy?.fontSrc ?? []);
  const imageDomains = uniqueSources([
    ...(manifest.allowed_resource_domains ?? []),
    ...(opts.policy?.imgSrc ?? []),
  ]);
  const scriptDomains = uniqueSources(opts.policy?.scriptSrc ?? []);
  const frameDomains = uniqueSources(opts.policy?.frameSrc ?? []);
  const workerDomains = uniqueSources(opts.policy?.workerSrc ?? []);
  const manifestDomains = uniqueSources(opts.policy?.manifestSrc ?? []);

  const directives: Array<[string, string]> = [
    ["default-src", "'self'"],
    ["script-src", ["'self'", "'unsafe-inline'", ...scriptDomains].join(' ')],
    ["style-src", ["'self'", "'unsafe-inline'", ...styleDomains].join(' ')],
    ["img-src", ["'self'", 'data:', 'blob:', ...imageDomains].join(' ')],
    ["font-src", ["'self'", 'data:', ...fontDomains].join(' ')],
    ["frame-src", ["'self'", ...frameDomains].join(' ')],
    [
      "connect-src",
      ["'self'", ...connectDomains].join(' '),
    ],
    ["worker-src", ["'self'", 'blob:', ...workerDomains].join(' ')],
    ["manifest-src", ["'self'", ...manifestDomains].join(' ')],
    ["base-uri", "'self'"],
    ["frame-ancestors", PLATFORM_FRAME_ANCESTORS],
  ];

  const header = directives.map(([k, v]) => `${k} ${v}`).join('; ');
  const metaTag = `<meta http-equiv="Content-Security-Policy" content="${escapeHtml(header)}">`;

  return { header, metaTag };
}

function uniqueSources(values: readonly string[]): string[] {
  return [...new Set(values.map(formatCspSource).filter(Boolean))].sort();
}

function formatCspSource(domain: string): string {
  const trimmed = domain.trim();
  if (!trimmed) return '';
  // Hostnames get `https://` prefix unless they already have a scheme.
  if (/^(?:https?|wss?):\/\//i.test(trimmed)) return trimmed;
  if (trimmed.startsWith('*.')) return `https://${trimmed}`;
  return `https://${trimmed}`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
