/**
 * PrintView — the clinician-handoff layout.
 *
 * Caller passes a `ReportData` (built from `pdf-data.ts`) and the
 * recipient's name. We render a print-CSS friendly page; the user
 * triggers `window.print()` from a button up in Report.tsx.
 *
 * Voice: factual, neutral. No commentary on the recipient's
 * behaviour or compliance.
 */
import type { ReportData } from '../lib/pdf-data.ts';

interface Props {
  data: ReportData;
  recipientName: string;
}

function fmtTime(ms: number): string {
  return new Date(ms).toLocaleString(undefined, {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

function fmtDate(ms: number): string {
  return new Date(ms).toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

export function PrintView({ data, recipientName }: Props) {
  const subject = recipientName || 'the care recipient';
  return (
    <div className="cl-print-view">
      <header className="cl-print-head">
        <h1>Care record · {subject}</h1>
        <p className="cl-print-range">
          {data.startISO} to {data.endISO}
        </p>
      </header>

      <section className="cl-print-section">
        <h2>Active medications</h2>
        {data.meds.length === 0 ? (
          <p className="cl-mute">No medications recorded in this range.</p>
        ) : (
          <table className="cl-print-table">
            <thead>
              <tr>
                <th>Medication</th>
                <th>Dose</th>
                <th>Schedule</th>
                <th>Given</th>
                <th>Missed</th>
              </tr>
            </thead>
            <tbody>
              {data.meds.map((m) => (
                <tr key={m.med.id}>
                  <td>{m.med.name}</td>
                  <td>{m.med.dose || '—'}</td>
                  <td>{m.med.schedule_text || '—'}</td>
                  <td>{m.doseCountInRange}</td>
                  <td>{m.missedCountInRange}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>

      <section className="cl-print-section">
        <h2>Dose history</h2>
        {data.doses.length === 0 ? (
          <p className="cl-mute">No doses recorded.</p>
        ) : (
          <table className="cl-print-table">
            <thead>
              <tr>
                <th>When</th>
                <th>Medication</th>
                <th>Status</th>
                <th>Caregiver</th>
                <th>Note</th>
              </tr>
            </thead>
            <tbody>
              {data.doses.map((d) => {
                const med = data.meds.find((m) => m.med.id === d.med_id)?.med;
                return (
                  <tr key={d.id}>
                    <td>{fmtTime(d.given_at)}</td>
                    <td>{med?.name ?? '(unknown)'}</td>
                    <td>{d.missed ? 'missed' : 'given'}</td>
                    <td>caregiver {d.given_by.toUpperCase()}</td>
                    <td>{d.note}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </section>

      <section className="cl-print-section">
        <h2>Symptom log</h2>
        {data.symptoms.length === 0 ? (
          <p className="cl-mute">No symptoms recorded.</p>
        ) : (
          <table className="cl-print-table">
            <thead>
              <tr>
                <th>When</th>
                <th>Symptom</th>
                <th>Intensity</th>
                <th>Note</th>
              </tr>
            </thead>
            <tbody>
              {data.symptoms.map((s) => (
                <tr key={s.id}>
                  <td>{fmtTime(s.occurred_at)}</td>
                  <td>{s.label}</td>
                  <td>{s.intensity >= 1 ? `${s.intensity}/5` : 'noted'}</td>
                  <td>{s.note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>

      {data.handover.length > 0 ? (
        <section className="cl-print-section">
          <h2>Handover notes (selected)</h2>
          <ul className="cl-print-handover">
            {data.handover.map((h) => (
              <li key={h.id}>
                <strong>{fmtDate(h.written_at)}</strong> · caregiver {h.author.toUpperCase()}: {h.body}
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <footer className="cl-print-foot">
        <p>Generated by Care Log. Records stay on the paired devices.</p>
      </footer>
    </div>
  );
}
